import test from 'node:test';
import assert from 'node:assert/strict';
import {createAnswerStream} from '../src/answer-stream.mjs';
import {consumeSse} from '../src/sse.mjs';
function harness(){let callback,time=0,settled=0,latest;const updates=[];const stream=createAnswerStream({modelIds:['a','b'],schedule:fn=>{callback=fn;return 1},cancel:()=>{callback=null},random:()=>.4,reduced:()=>false,onUpdate:s=>{latest=s;updates.push(s)},onSettled:()=>settled++});return{stream,updates,get latest(){return latest},get settled(){return settled},step(ms=32){time+=ms;const fn=callback;callback=null;fn?.(time)},drain(){for(let i=0;i<1000&&callback;i++)this.step(100)}}}
test('independent chunks are visible before completion, punctuation pauses, Unicode survives',()=>{const h=harness();h.stream.push('a','你好，👩你好世界。下一段。');h.step();assert.equal(h.latest[0].text,'你好，');assert.equal(h.latest[1].text,'');h.step(20);assert.equal(h.latest[0].text,'你好，');h.stream.push('b','乙模型');h.stream.end('b');h.step(40);assert.equal(h.latest[1].status,'done');assert.equal(h.latest[0].status,'streaming');h.stream.end('a');h.drain();assert.equal(h.latest[0].text,'你好，👩你好世界。下一段。');assert.equal(h.settled,1)});
test('stop preserves received buffers and ignores late chunks',()=>{const h=harness();h.stream.push('a','还有未显示的文本');h.step();h.stream.stop();const stopped=h.latest;assert.equal(stopped[0].text,'还有未显示的文本');assert.equal(stopped[0].status,'stopped');h.stream.push('a','迟到污染');h.drain();assert.deepEqual(h.latest,stopped);assert.equal(h.settled,1)});
test('one failure retains partial text and does not stop the other model',()=>{const h=harness();h.stream.push('a','半段回答');h.stream.end('a',{error:'超时'});h.drain();assert.equal(h.latest[0].status,'error');assert.equal(h.latest[0].text,'半段回答');assert.equal(h.settled,0);h.stream.push('b','成功');h.stream.end('b');h.drain();assert.equal(h.latest[1].status,'done');assert.equal(h.settled,1)});
test('empty completion, final full text reconciliation, disposal and premature EOF',()=>{const h=harness();h.stream.end('a',{fullText:'完整回答'});h.stream.fail('提前关闭');h.drain();assert.equal(h.latest[0].text,'完整回答');assert.equal(h.latest[1].error,'提前关闭');const k=harness();k.stream.push('a','不能再绘制');k.stream.dispose();k.drain();assert.equal(k.updates.length,0)});
test('SSE survives split UTF-8, CRLF, multiline JSON and final event without delimiter',async()=>{const str='event: chunk\r\ndata: {"modelId":"a",\r\ndata: "delta":"你好😀"}\r\n\r\nevent: done\ndata: {"modelId":"a"}';const bytes=new TextEncoder().encode(str),seen=[];const body=new ReadableStream({start(c){for(const byte of bytes)c.enqueue(new Uint8Array([byte]));c.close()}});await consumeSse(body,{onChunk:d=>seen.push(d.delta),onDone:d=>seen.push(d.modelId)});assert.deepEqual(seen,['你好😀','a'])});
test('reduced motion shows received content without simulated typing',()=>{let tick,latest;const stream=createAnswerStream({modelIds:['a'],schedule:fn=>{tick=fn;return 1},cancel:()=>{},reduced:()=>true,onUpdate:s=>latest=s});stream.push('a','第一段。\n第二段完整显示。');stream.end('a');tick(10);assert.equal(latest[0].text,'第一段。\n第二段完整显示。');assert.equal(latest[0].status,'done')});
