import test from 'node:test';
import assert from 'node:assert/strict';
import {newRubric,createTask,addExperiment,saveRun,retryRun,acceptanceStatus,qualityScore,summarize,modelSummaries,taskReport,detailCSV,summaryCSV,rawPackage} from '../src/evaluations.mjs';
const options=()=>({name:'客服模型选型',module:'text',models:[{id:'a',name:'模型A',apiId:'a-v1',version:'2026-01'},{id:'b',name:'模型B'}],cases:[{id:'case1',title:'退款',question:'退款怎么办？',systemPrompt:'准确回答',evaluation:{module:'text',acceptance:['说明退款条件'],severe:['编造政策'],references:'规则原文'}}],dimensions:newRubric('text')});
const ready=(task,run,patch={})=>({...run,status:'success',output:'原始回答',acceptance:{0:'pass'},severe:{0:'no'},scores:Object.fromEntries(task.dimensions.map(d=>[d.id,5])),...patch});
test('task snapshots freeze cases, model versions and rubric without carrying credentials',()=>{const o=options();o.models[0].apiKey='secret';const t=createTask(o,'t');o.models[0].name='changed';o.cases[0].question='changed';o.dimensions[0].weight=99;assert.equal(t.models[0].name,'模型A');assert.equal(t.models[0].apiKey,undefined);assert.equal(t.cases[0].question,'退款怎么办？');assert.equal(t.dimensions[0].weight,30);assert.throws(()=>createTask({...options(),dimensions:[{id:'x',name:'x',weight:10}]}),/100/)});
test('hard gate and quality remain independent; missing values are not zeros',()=>{const t=addExperiment(createTask(options()),'case1'),r=ready(t,t.runs[0]);assert.equal(qualityScore(t,r).score,100);assert.equal(acceptanceStatus(t,r),'pass');assert.equal(acceptanceStatus(t,{...r,severe:{0:'yes'}}),'fail');assert.equal(qualityScore(t,{...r,severe:{0:'yes'}}).score,100);assert.equal(qualityScore(t,{...r,scores:{d0:5}}).score,null);assert.equal(acceptanceStatus(t,{...r,severe:{}}),'pending');assert.equal(acceptanceStatus(t,{...r,status:'error'}),'fail')});
test('N/A removes only its weight; all N/A is not a zero score',()=>{const t=addExperiment(createTask(options()),'case1'),r=ready(t,t.runs[0],{scores:{d0:'na',d1:1,d2:5,d3:5,d4:5}});assert.equal(qualityScore(t,r).score,71.4);assert.throws(()=>saveRun(t,r),/不适用/);assert.doesNotThrow(()=>saveRun(t,{...r,note:'此任务无需事实核查'}));assert.equal(qualityScore(t,{...r,scores:Object.fromEntries(t.dimensions.map(d=>[d.id,'na']))}).score,null)});
test('retries do not inflate repeats or first pass; costs include failed attempts',()=>{let t=addExperiment(createTask(options()),'case1');const id=t.runs[0].id;t=saveRun(t,ready(t,t.runs[0],{acceptance:{0:'fail'},metrics:{cost:.2,latency:2,inputTokens:null,outputTokens:null},measurementNote:'账单'}));t=retryRun(t,id);assert.throws(()=>retryRun(t,id),/已有重试/);t=saveRun(t,ready(t,t.runs.at(-1),{metrics:{cost:.3,latency:3,inputTokens:null,outputTokens:null},measurementNote:'账单'}));const s=summarize(t).find(s=>s.modelId==='a');assert.equal(s.repetitions,1);assert.equal(s.retries,1);assert.equal(s.firstPass,0);assert.equal(s.firstEvaluated,1);assert.equal(s.accepted,1);assert.equal(s.costPerAccepted,.5);assert.equal(s.latency,2.5);assert.equal(t.runs[0].acceptance[0],'fail')});
test('new independent trials increment repetitions; incomplete, demo and zero accepted metrics stay explicit',()=>{let t=addExperiment(createTask(options()),'case1');t=addExperiment(t,'case1');assert.equal(t.runs[2].repetition,2);assert.equal(summarize(t)[0].costStatus,'待完成验收');t=saveRun(t,ready(t,t.runs[0],{acceptance:{0:'fail'}}));assert.equal(summarize(t)[0].costPerAccepted,null);t=addExperiment(t,'case1','demo');t=saveRun(t,ready(t,t.runs.at(-2),{metrics:{cost:2,latency:3},measurementNote:'演示数据'}));const s=summarize(t).find(s=>s.modelId==='a'&&s.source==='demo');assert.equal(s.latency,null);assert.equal(s.costTotal,null);assert.equal(s.accepted,1);assert.equal(s.repetitions,1)});
test('failed calls, missing costs and partial applicability do not yield misleading averages',()=>{let t=addExperiment(createTask(options()),'case1');t=saveRun(t,{...t.runs[0],status:'error',failure:'超时'});let s=summarize(t)[0];assert.equal(s.costStatus,'无合格成果');assert.equal(s.quality,null);t=addExperiment(t,'case1');t=saveRun(t,ready(t,t.runs[2]));s=summarize(t)[0];assert.equal(s.costTotal,null);assert.equal(s.costStatus,'未采集');t=addExperiment(t,'case1');t=saveRun(t,ready(t,t.runs[4],{scores:{d0:'na',d1:5,d2:5,d3:5,d4:5},note:'无需事实核查'}));s=summarize(t)[0];assert.equal(s.comparable,false);assert.equal(s.quality,null)});
test('result validation rejects empty success, failed calls without explanation and unlabeled measurements',()=>{const t=addExperiment(createTask(options()),'case1'),r=t.runs[0];assert.throws(()=>saveRun(t,{...r,status:'success'}),/原始输出/);assert.throws(()=>saveRun(t,{...r,status:'error'}),/失败原因/);assert.throws(()=>saveRun(t,{...r,metrics:{cost:-1}}),/非负/);assert.throws(()=>saveRun(t,{...r,metrics:{cost:0}}),/记录来源/);assert.throws(()=>saveRun(t,{...r,metrics:{inputTokens:.5}}),/整数/)});
test('all report formats preserve evidence, conditions, missing metrics and formula-safe CSV',()=>{let t=addExperiment(createTask({...options(),conditions:'temperature 0.2'}),'case1');t=saveRun(t,ready(t,t.runs[0],{output:'=SUM(A1)\n"原文"',evidence:'引用第二段',location:'第2段',reviewer:'小谢'}));const md=taskReport(t),csv=detailCSV(t),summary=summaryCSV(t),raw=JSON.parse(rawPackage(t));for(const text of ['引用第二段','temperature 0.2','未采集','小谢','无额外']){if(text!=='无额外')assert.ok(md.includes(text),text)}assert.ok(csv.includes("'=SUM(A1)"));assert.ok(csv.includes('""原文""'));assert.ok(summary.includes('首过率'));assert.equal(raw.task.runs[0].output,'=SUM(A1)\n"原文"');assert.equal(raw.task.models[0].version,'2026-01')});
test('four module templates sum to 100 and seed imports never manufacture telemetry',()=>{for(const m of ['text','image','video','code'])assert.equal(newRubric(m).reduce((s,d)=>s+d.weight,0),100);const t=createTask({...options(),seed:{outputs:['demo1','demo2'],plans:[{model:'A',seconds:2.1},{model:'B',seconds:3}],sourceRef:'conversation/turn'}});assert.equal(t.runs.length,2);assert.equal(t.runs[0].source,'demo');assert.equal(t.runs[0].metrics.latency,null);assert.equal(t.runs[0].originalPlan.seconds,2.1);assert.equal(summarize(t)[0].latency,null)});

test('model rollups weight cases equally and withhold totals until all required scores exist',()=>{
 const o=options();o.cases.push({...structuredClone(o.cases[0]),id:'case2',title:'其他场景'});
 let t=createTask(o);t=addExperiment(t,'case1');t=saveRun(t,ready(t,t.runs[0]));
 assert.equal(modelSummaries(t)[0].quality,null);
 t=addExperiment(t,'case2');t=saveRun(t,ready(t,t.runs[2],{scores:Object.fromEntries(t.dimensions.map(d=>[d.id,1]))}));
 assert.equal(modelSummaries(t)[0].quality,50);
 t=addExperiment(t,'case1');assert.equal(modelSummaries(t)[0].quality,null);
 t=saveRun(t,ready(t,t.runs[4]));assert.equal(modelSummaries(t)[0].quality,50);
 assert.ok(summaryCSV(t).includes('模型总览'));
});
test('retry parents cannot be overwritten and identity/source cannot be changed while saving',()=>{
 let t=addExperiment(createTask(options()),'case1');const original=t.runs[0];t=saveRun(t,{...original,status:'error',failure:'timeout'});t=retryRun(t,original.id);
 assert.throws(()=>saveRun(t,ready(t,original)),/只读/);
 const retry=t.runs.at(-1);t=saveRun(t,ready(t,{...retry,source:'demo',modelId:'fake',caseId:'wrong',repetition:99}));
 assert.equal(t.runs.at(-1).source,'manual');assert.equal(t.runs.at(-1).modelId,'a');assert.equal(t.runs.at(-1).repetition,1);
});
test('task limits and demo-only retry restrictions remain explicit',()=>{
 const o=options();assert.throws(()=>createTask({...o,models:Array.from({length:10},(_,i)=>({id:String(i),name:'M'+i}))}),/2–9/);
 assert.throws(()=>createTask({...o,cases:[{...o.cases[0],evaluation:{...o.cases[0].evaluation,module:'image'}}]}),/同一模块/);
 const t=createTask({...o,seed:{outputs:['demo1','demo2'],plans:[{model:'A',apiKey:'never-copy'},{model:'B'}],ratings:{0:{score:4,note:'原始备注'}}}});
 assert.equal(t.runs[0].originalPlan.apiKey,undefined);assert.equal(t.runs[0].legacyScore,4);assert.equal(t.runs[0].note,'原始备注');assert.throws(()=>retryRun(t,t.runs[0].id),/演示记录/);
});
test('business adoption, actual runtime and rework remain part of exported raw evidence',()=>{
 let t=addExperiment(createTask(options()),'case1');t=saveRun(t,ready(t,t.runs[0],{adoption:'修改后采纳',reworkMinutes:'12.5',executedAt:'2026-09-22 10:00 +08:00'}));
 assert.equal(t.runs[0].reworkMinutes,12.5);assert.ok(detailCSV(t).includes('返工分钟'));assert.ok(taskReport(t).includes('修改后采纳'));assert.ok(rawPackage(t).includes('2026-09-22 10:00 +08:00'));
});
