import React,{useState,useRef,useEffect} from 'react';
import {createRoot} from 'react-dom/client';
import {ConfigProvider,App as AntApp,theme,Button,Input,Select,Drawer,Form,Checkbox,Table,Segmented,Dropdown,Modal} from 'antd';
import {ProCard} from '@ant-design/pro-components';
import {ArrowLeftRightIcon,SearchIcon,CopyIcon,SettingsIcon,PlusIcon,ArrowRightIcon,ArrowUpIcon,BookOpenIcon,HistoryIcon,CheckIcon,XIcon,DownloadIcon,SlidersHorizontalIcon,MessageSquareIcon,ChevronDownIcon,MenuIcon,RefreshCwIcon,FileTextIcon,CheckCheckIcon,SunIcon,MoonIcon,ImageIcon,TypeIcon,VideoIcon,CodeIcon,EllipsisIcon,PinIcon,PencilIcon,Trash2Icon} from '@animateicons/react/lucide';
import 'antd/dist/reset.css';
import './arena.css';
import StreamedAnswer from './streamed-answer.jsx';
import {createAnswerStream,answerMarkdown} from './answer-stream.mjs';
import {CompareTypeMenu,AttachMenu,ComposerSurface,AttachmentList,useAttachments} from './composer-controls.jsx';
import {attachmentSnapshots,attachmentText,questionWithAttachments} from './attachments.mjs';
import AnswerFeedback from './answer-feedback.jsx';
import PromptLibrary,{PromptIcon} from './prompt-library.jsx';
import {homePrompts} from './prompt-library.mjs';
import {modelFeedback,bulkFeedbackPatch,feedbackPatch,feedbackText} from './feedback.mjs';
import {ComposerBeam,ModelStatus} from './motion-ui.jsx';
import duizhaoLogoLight from './assets/duizhao-wordmark-light.png';
import duizhaoLogoDark from './assets/duizhao-wordmark-dark.png';
import ImageAnswers,{IMAGE_PROMPT,imagePlans,imageSample} from './image-demo.jsx';
import CodeAnswers,{CODE_PROMPT,codePlans,codeSample} from './code-demo.jsx';
import {DEFAULT_SCHEMES,snapshotScheme,c2cPlans,csvText} from './c2c.mjs';
import {C2CConnection,C2CSchemes,ResultReview} from './c2c-ui.jsx';
import Evaluations from './evaluations-ui.jsx';
import {asConversation,appendConversationTurn,updateConversationTurn,sortConversations,renameConversation} from './conversations.mjs';
import {createCompare,streamCompare,cancelCompare,getStore,putStore,getSettings,putSettings,listModels} from './api.mjs';

const DEFAULT_PROMPT='你是一位资深产品经理。请覆盖正常流程、异常情况和验收标准，明确需要业务方补充的信息。';
const TEMPLATES=[
 {title:'写一份产品需求',desc:'比较业务完整性与可执行性',question:'请为「用户取消订单后申请退款」写一份需求说明，包含正常流程、异常情况和验收标准。',kind:'refund',icon:FileTextIcon},
 {title:'找出异常边界',desc:'检查重复操作、超时与失败',question:'退款申请遇到重复点击、支付渠道超时和重复回调时，分别应该怎么处理？',kind:'refund',icon:ArrowLeftRightIcon},
 {title:'设计无答案体验',desc:'看看 AI 如何面对不确定',question:'企业知识库找不到答案时，应该如何提示用户、追问并转接人工？',kind:'knowledge',icon:MessageSquareIcon},
 {title:'检查客服规范',desc:'比较回答要求与约束覆盖',question:'请给出一份客服助手的回答规范，要求准确、简洁，并在信息不足时主动澄清。',kind:'knowledge',icon:SlidersHorizontalIcon},
 {title:'生成验收清单',desc:'把需求变成可检查的条目',question:'把订单退款流程整理为验收清单，覆盖正常情况和异常情况。',kind:'refund',icon:CheckCheckIcon},
 {title:'评审交互方案',desc:'发现缺失的反馈与恢复路径',question:'用户上传文件失败时，产品应该提供哪些提示、状态和重试入口？',kind:'upload',icon:BookOpenIcon}
];
const CONTENT={refund:[
 {lead:'订单退款需求说明',intro:'用户取消符合条件的订单后，可以申请原路退款，并查看处理进度。',sections:[['正常流程',['进入订单详情，选择「取消订单」。','确认取消原因、可退金额和退款去向。','提交申请后，显示「退款处理中」。','退款完成后，通过站内消息通知用户。']],['异常情况',['退款失败时展示原因，提供查询进度和联系客服的入口。','网络异常时保留当前输入，允许用户重新提交。']],['验收标准',['退款金额与实付金额一致。','订单页能展示处理中、成功和失败三种状态。']]],end:'待确认：支持退款的订单状态、退款到账时效。'},
 {lead:'先明确规则，再定义状态',intro:'把取消订单与资金退款分开处理。用户需要知道退多少、退到哪里，以及下一步可以做什么。',sections:[['业务规则与主流程',['未付款订单取消后，不发起退款。','已付款订单先校验可退金额，再由用户确认。','提交后生成唯一申请号，锁定重复提交入口。']],['需要覆盖的异常边界',['重复点击：使用同一个申请标识，不重复退款。','渠道超时：先查询原申请状态，避免直接发起新退款。','重复回调：只更新一次结果，保留原始处理记录。']],['可执行的验收检查',['重复提交同一申请，只产生一次资金操作。','刷新页面后，仍能查询同一笔退款的最新状态。']]],end:'待业务确认：优惠分摊、部分退款范围、人工处理时限。'},
 {lead:'从验收角度检查退款链路',intro:'把流程拆成申请、受理、处理中和终态，为每个状态定义可见反馈。',sections:[['核心检查项',['未付款订单不调用退款接口。','同一订单累计退款不超过剩余可退金额。','失败后保留申请号，支持查询和人工处理。']],['验证方法',['模拟渠道超时、重复回调和用户连续点击。','检查金额、订单状态与通知是否一致。']]],end:'这是一组演示验收条目，需要结合真实业务规则补充。'}],
 knowledge:[
 {lead:'找不到答案时，给用户下一步',intro:'先明确告知当前知识库没有足够信息，再帮助用户补充问题。',sections:[['回答流程',['说明暂时无法找到对应内容。','询问产品名称、版本或使用场景。','提供相关文档入口，仍未解决时转接人工。']],['用户提示',['“暂时没有找到足够的信息，可以补充一下具体场景吗？”','保存本次问题，方便后续完善知识库。']]],end:'待确认：人工服务时段与转接渠道。'},
 {lead:'区分“没有资料”和“问题不清楚”',intro:'避免用看起来合理的答案掩盖信息缺口。先判断能否回答，再选择澄清或转接。',sections:[['三种情况分别处理',['问题含糊：只追问一个最关键的缺失信息。','资料缺失：明确无法确认，展示相关信息的适用边界。','资料冲突：说明差异与来源时间，不擅自作结论。']],['转接与反馈',['保留问题和已补充的上下文，减少用户重复描述。','显示人工可用时段，并给出可选的留资入口。']],['验收关注',['没有依据时不编造操作步骤。','用户拒绝补充信息后，仍能选择结束或转人工。']]],end:'待确认：资料版本规则、转接权限和上下文保留范围。'},
 {lead:'用检查项约束回答',intro:'每次回答都检查依据、适用范围和下一步。',sections:[['检查项',['能否定位到支持回答的资料？','是否需要澄清版本或场景？','是否清楚说明未知信息？','用户能否顺利转接人工？']]],end:'实际验收需要包含无资料、冲突资料和问题含糊三类样本。'}],
 upload:[
 {lead:'上传失败的恢复流程',intro:'保留用户已选择的文件，清楚告知失败原因，并提供重试。',sections:[['基本反馈',['展示文件名、上传进度和当前状态。','网络中断时提示检查连接。','文件格式不支持时，列出支持的格式。']],['恢复入口',['提供重新上传和移除文件两个操作。','重试成功后清除错误提示。']]],end:'待确认：文件大小限制、格式范围和超时时间。'},
 {lead:'让错误对应具体的恢复动作',intro:'区分可重试的临时错误和必须修改文件的问题，避免用户反复点击无效操作。',sections:[['分类处理',['网络中断：保留文件选择，允许手动重试。','文件过大：展示大小上限，引导更换文件。','服务异常：保留任务状态，给出稍后重试提示。']],['状态与可访问性',['上传期间支持取消，取消后不显示成功。','用文字和图标说明错误，不只改变颜色。']],['验收检查',['连续点击重试不会生成重复任务。','取消后的迟到响应不会恢复成功状态。']]],end:'待确认：是否支持断点续传，以及临时文件保留时长。'},
 {lead:'上传错误验收清单',intro:'关注状态正确性与用户恢复成本。',sections:[['关键场景',['断网、超时、文件超限、格式错误。','取消上传后重新选择文件。','连续重试与迟到响应。']]],end:'按实际接口约束定义通过标准。'}]
};
function Answer({data}){return <><h2>{data.lead}</h2><p>{data.intro}</p>{data.sections.map(([title,items])=><section key={title}><h3>{title}</h3><ul>{items.map(x=><li key={x}>{x}</li>)}</ul></section>)}<div className="answer-end">{data.end}</div></>}
function MotionButton({icon:Icon,size=18,children,className='',...props}){
 const icon=useRef(null);
 const start=()=>{if(!props.disabled)icon.current?.startAnimation()};
 const stop=()=>icon.current?.stopAnimation();
 return <button {...props} className={className} onMouseEnter={start} onMouseLeave={stop} onFocus={start} onBlur={stop}><Icon ref={icon} size={size}/>{children}</button>;
}
function TextShimmer({children,duration=1,className=''}){return <span className={'text-shimmer '+(className||'')} style={{'--shimmer-duration':duration+'s'}}>{children}</span>}
const LETTERS='ABCDEFGHI';
const CATALOG=[
 ['Qwen Plus','通义千问','通用对话','qwen-plus'],['DeepSeek V3','DeepSeek','通用对话','deepseek-v3'],
 ['Qwen Turbo','通义千问','快速响应','qwen-turbo'],['DeepSeek R1','DeepSeek','深度推理','deepseek-r1'],
 ['Qwen Max','通义千问','通用对话','qwen-max'],['GLM 4','智谱','通用对话','glm-4'],
 ['Kimi','月之暗面','长文本','请填写实际模型 ID'],['Doubao Pro','豆包','通用对话','请填写实际模型 ID'],
 ['自定义业务模型','自定义','通用对话','请填写实际模型 ID']
].map(([name,provider,category,apiId],i)=>({id:'m'+i,name,provider,category,apiId}));
const read=(key,fallback)=>{try{return JSON.parse(localStorage.getItem(key))??fallback}catch{return fallback}};
const makePlans=(ids,catalog,prompt)=>ids.map(id=>({...catalog.find(m=>m.id===id),model:catalog.find(m=>m.id===id).name,prompt}));
const initialRecords=[{id:'sample-refund',title:'退款需求：正常流程与异常边界',question:TEMPLATES[0].question,kind:'refund',plans:makePlans(['m0','m1'],CATALOG,DEFAULT_PROMPT),date:'示例记录',vote:null},{id:'sample-knowledge',title:'知识库找不到答案，应该怎么回应？',question:TEMPLATES[2].question,kind:'knowledge',plans:makePlans(['m0','m1'],CATALOG,DEFAULT_PROMPT),date:'示例记录',vote:null}];
function Workspace({appearance,onAppearanceChange}){
 const streamingPreview=new URLSearchParams(location.search).get('demo')==='streaming';
 const loadingPreview=new URLSearchParams(location.search).get('demo')==='loading';
 const {message,modal}=AntApp.useApp();
 const [screen,setScreen]=useState(()=>location.hash==='#evaluations'?'evaluations':location.hash==='#library'?'library':location.hash==='#models'?'models':'arena'),[sidebar,setSidebar]=useState(false),[collapsed,setCollapsed]=useState(false);
 const [modality,setModality]=useState(()=>new URLSearchParams(location.search).get('demo')==='image'?'image':'text'),[imageCount,setImageCount]=useState(2);
 const [draft,setDraft]=useState(()=>new URLSearchParams(location.search).get('demo')==='image'?IMAGE_PROMPT:new URLSearchParams(location.search).get('demo')==='c2c'?TEMPLATES[0].question:''),[kind,setKind]=useState('refund'),[current,setCurrent]=useState(()=>streamingPreview?asConversation({...initialRecords[1],id:'stream-preview',plans:initialRecords[1].plans.map(p=>({...p,text:'',status:'waiting'}))}):loadingPreview?asConversation({...initialRecords[0],id:'loading-preview'}):null),[busy,setBusy]=useState(loadingPreview),[finished,setFinished]=useState(0);
 const [catalog,setCatalog]=useState(()=>read('arena-models-v2',CATALOG)),[selected,setSelected]=useState(()=>read('arena-selected-v2',['m0','m1'])),[prompt,setPrompt]=useState(()=>read('arena-prompt-v2',DEFAULT_PROMPT));
 const [library,setLibrary]=useState(()=>read('arena-prompt-library-v1',TEMPLATES.map((t,i)=>({...t,id:'template-'+i,icon:['file','compare','message','settings','check','book'][i],systemPrompt:DEFAULT_PROMPT,home:true}))));
 const [evaluationTasks,setEvaluationTasks]=useState(()=>read('arena-evaluation-tasks-v1',[])),[evaluationSeed,setEvaluationSeed]=useState(null);
 const [records,setRecords]=useState(()=>read('arena-records-v2',initialRecords).map(asConversation));
 const [renameTarget,setRenameTarget]=useState(null),[topicTitle,setTopicTitle]=useState('');
 const [panel,setPanel]=useState(null),[search,setSearch]=useState(''),[modelQuery,setModelQuery]=useState(''),[category,setCategory]=useState('全部模型'),[view,setView]=useState('all'),[notes,setNotes]=useState(''),[expanded,setExpanded]=useState(null),[editing,setEditing]=useState(null),[exporting,setExporting]=useState(false);
 const [connection,setConnection]=useState('我的蚂蚁 MaaS'),[url,setUrl]=useState('https://maas-api.antdigital.com/v1');
 const [compareMode,setCompareMode]=useState(()=>new URLSearchParams(location.search).get('demo')==='c2c'?'c2c':'models'),[modelTab,setModelTab]=useState('models'),[connectionTab,setConnectionTab]=useState('maas');
 const [schemes,setSchemes]=useState(()=>read('arena-c2c-schemes',DEFAULT_SCHEMES)),[schemeId,setSchemeId]=useState(()=>read('arena-c2c-selected','c2c-small')),[c2cConnection,setC2cConnection]=useState(()=>read('arena-c2c-connection',{address:''}));
 const activeScheme=schemes.find(s=>s.id===schemeId)||schemes[0],isC2C=compareMode==='c2c'&&modality==='text';
 const saveSchemes=next=>{setSchemes(next);store('arena-c2c-schemes',next)};
 const selectScheme=id=>{setSchemeId(id);store('arena-c2c-selected',id)};
 const showC2CSettings=()=>{setConnectionTab('c2c');setPanel('settings')};
 const useScheme=id=>{selectScheme(id);setCompareMode('c2c');setModality('text');returnArena();message.success('已选择协作方案，可开始演示对比')};
 const attachments=useAttachments();
 const currentRef=useRef(current);currentRef.current=current;
 const input=useRef(null),footer=useRef(null),latestTurn=useRef(null),activeStream=useRef(null);const [composerH,setComposerH]=useState(210),[backendKeys,setBackendKeys]=useState([]),[keyDraft,setKeyDraft]=useState({}),[savingKeys,setSavingKeys]=useState(false);
 const store=(key,value)=>{try{localStorage.setItem(key,JSON.stringify(value))}catch{message.warning('浏览器无法保存，当前页面仍可使用')}};
const loadBackendKeys=async()=>{try{const models=await listModels();const seen=new Map();for(const m of models){if(m.keyRef&&!seen.has(m.keyRef))seen.set(m.keyRef,{ref:m.keyRef,label:m.provider,configured:m.keyConfigured})}setBackendKeys([...seen.values()])}catch{}};
const saveKeys=async()=>{setSavingKeys(true);try{const res=await putSettings(keyDraft);const configured=res.configured||{};setBackendKeys(ks=>ks.map(k=>({...k,configured:!!configured[k.ref]})));setKeyDraft({});message.success('密钥已保存')}catch{message.error('保存失败，请确认后端已启动')}finally{setSavingKeys(false)}};
useEffect(()=>{if(panel==='settings')loadBackendKeys()},[panel]);
 useEffect(()=>{if(streamingPreview)startAnswers(currentRef.current,{demo:true});return()=>disposeStream()},[]);
 useEffect(()=>{if(!footer.current)return;const o=new ResizeObserver(([e])=>setComposerH(e.contentRect.height+28));o.observe(footer.current);return()=>o.disconnect()},[!!current,screen]);
 useEffect(()=>{const f=e=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){e.preventDefault();setPanel('search')}if(e.key==='Escape')setSidebar(false)};window.addEventListener('keydown',f);return()=>window.removeEventListener('keydown',f)},[]);
 useEffect(()=>{(async()=>{try{const remote=await getStore('arena-records-v2');if(remote===null){putStore('arena-records-v2',read('arena-records-v2',initialRecords)).catch(()=>{})}else{setRecords(remote.map(asConversation));try{localStorage.setItem('arena-records-v2',JSON.stringify(remote))}catch{}}}catch{}})()},[]);
 const screenRef=useRef(screen);screenRef.current=screen;
 const navigateScreen=next=>{screenRef.current=next;setScreen(next);location.hash=next==='arena'?'':next};
 useEffect(()=>{const update=()=>{const next=location.hash==='#evaluations'?'evaluations':location.hash==='#library'?'library':location.hash==='#models'?'models':'arena';if(next===screenRef.current)return;setScreen(next);setPanel(null);setSidebar(false);window.scrollTo(0,0)};window.addEventListener('hashchange',update);return()=>window.removeEventListener('hashchange',update)},[]);
 const showLibrary=()=>{navigateScreen('library');setPanel(null);setSidebar(false);window.scrollTo(0,0)};
 const showEvaluations=()=>{navigateScreen('evaluations');setPanel(null);setSidebar(false);window.scrollTo(0,0)};
 const saveEvaluationTasks=next=>{try{localStorage.setItem('arena-evaluation-tasks-v1',JSON.stringify(next));setEvaluationTasks(next);return true}catch{message.error('测评保存失败：浏览器存储空间不足，请保留当前内容后重试。');return false}};
 const saveLibrary=next=>{try{localStorage.setItem('arena-prompt-library-v1',JSON.stringify(next));setLibrary(next);return true}catch{message.error('保存失败：浏览器存储空间不足，请保留当前内容后重试。');return false}};
 const persist=r=>{setRecords(r);store('arena-records-v2',r);putStore('arena-records-v2',r).catch(()=>{})};
 const commitConversation=r=>{currentRef.current=r;setCurrent(r);if(r.id==='stream-preview')return;setRecords(previous=>{const next=[r,...previous.filter(x=>x.id!==r.id)];store('arena-records-v2',next);putStore('arena-records-v2',next).catch(()=>{});return next})};
 const patchTurn=(id,patch)=>commitConversation(updateConversationTurn(currentRef.current,id,patch));
 const saveCurrent=r=>patchTurn(current.turns.at(-1).id,{vote:r.vote,notes:r.notes,checks:r.checks});
 const saveSelection=ids=>{setSelected(ids);store('arena-selected-v2',ids)};
 const showModels=()=>{navigateScreen('models');setSidebar(false);setPanel(null);window.scrollTo(0,0)};
 const returnArena=()=>{navigateScreen('arena');window.scrollTo(0,0)};
 const reset=()=>{stopAnswers();setBusy(false);currentRef.current=null;setCurrent(null);setDraft('');attachments.clear();navigateScreen('arena');setSidebar(false);setNotes('');window.scrollTo(0,0)};
 const openRecord=record=>{if(busy)return;const r=asConversation(record);attachments.clear();currentRef.current=r;setCurrent(r);setFinished(r.plans.length);setDraft('');setKind(r.kind);setModality(r.modality||'text');setCompareMode(r.compareMode||'models');if(r.scheme&&schemes.some(s=>s.id===r.scheme.id))selectScheme(r.scheme.id);if(r.modality==='image'||r.modality==='code')setImageCount(r.plans.length);setNotes(r.notes||'');setPanel(null);setSidebar(false);returnArena()};
 const updateTopic=updated=>{persist(records.map(r=>r.id===updated.id?updated:r));setCurrent(previous=>previous?.id===updated.id?{...previous,title:updated.title,pinned:updated.pinned}:previous)};
 const saveTopicTitle=()=>{if(!topicTitle.trim()){message.warning('请输入对话名称');return}const record=records.find(r=>r.id===renameTarget);if(record)updateTopic(renameConversation(record,topicTitle));setRenameTarget(null)};
 const topicAction=(record,key)=>{
  if(busy)return;
  if(key==='rename'){setRenameTarget(record.id);setTopicTitle(record.title)}
  if(key==='pin'){updateTopic({...record,pinned:!record.pinned});message.success(record.pinned?'已取消置顶':'已置顶')}
  if(key==='delete')modal.confirm({title:'删除这条对话？',content:'“'+record.title+'”及其全部回答和评价将被删除。',okText:'删除',cancelText:'取消',okButtonProps:{danger:true},onOk:()=>{persist(records.filter(r=>r.id!==record.id));if(current?.id===record.id){reset();setExpanded(null);setPanel(null)}message.success('对话已删除')}});
 };
 const choose=t=>{if(t.systemPrompt){setPrompt(t.systemPrompt);store('arena-prompt-v2',t.systemPrompt)}setModality(t.evaluation?.module||'text');setDraft(t.question);setKind(t.kind||'refund');setPanel(null);returnArena();setTimeout(()=>input.current?.focus(),0)};
 const useLibraryPrompt=t=>{reset();choose(t)};
 const dataFor=(i,turn=current)=>{const p=turn.plans[i];if(p.text!==undefined)return{type:'streamed',text:p.text,error:p.error,status:p.status,source:p.source};return turn.modality==='image'?{type:'image',asset:imageSample(p).id+'.png',description:imageSample(p).alt,source:'预置图片演示'}:turn.modality==='code'?{type:'code',code:codeSample(p).code,title:codeSample(p).title,lang:codeSample(p).lang,source:'预置代码演示'}:CONTENT[turn.kind][i%3]};
 function evaluateTurn(turn){
  const outputs=turn.plans.map((p,i)=>{const d=dataFor(i,turn);return d.type==='streamed'?d.text:d.type==='code'?d.code:d.type==='image'?'图片演示：'+d.description+'\n素材：'+d.asset:[d.lead,d.intro,...(d.sections||[]).flatMap(([title,items])=>[title,...items]),d.end].join('\n\n')});
  const history=current.turns.slice(0,current.turns.findIndex(t=>t.id===turn.id)).map((t,n)=>'第 '+(n+1)+' 轮问题：'+t.question+'\n'+t.plans.map((p,i)=>p.model+'：'+JSON.stringify(dataFor(i,t))).join('\n')).join('\n\n');
  setEvaluationSeed({module:turn.modality||'text',title:current.title,case:{id:crypto.randomUUID(),title:current.title,question:turn.question,systemPrompt:turn.plans[0]?.prompt||'',evaluation:{module:turn.modality||'text',references:[history?'原话题历史：\n'+history:'',attachmentText(turn.attachments)].filter(Boolean).join('\n\n')}},models:turn.plans.map((p,i)=>({...p,id:p.id||'plan-'+i,name:p.model})),plans:turn.plans,outputs,ratings:turn.ratings,notes:turn.notes,feedback:Object.fromEntries(turn.plans.map((_,i)=>[i,feedbackText(modelFeedback(turn,i))])),sourceRef:current.id+'/'+turn.id,date:turn.date});showEvaluations();
 }
 function run(){
  if(busy)return;if(attachments.items.some(a=>a.type!=='text')){message.warning('当前模型暂不支持读取文件，请移除文件后发送；文本附件可以正常发送。');return}if(modality==='video'){message.info('视频模型尚未接入，当前可先体验文本或图片演示');return}if(!draft.trim()){message.warning('先输入一道想比较的问题');return}
  const previous=current?updateConversationTurn(current,current.turns.at(-1).id,{notes}):null;
  const turn={id:crypto.randomUUID(),question:draft.trim(),attachments:attachmentSnapshots(attachments.items),kind,modality,compareMode:isC2C?'c2c':'models',scheme:isC2C?snapshotScheme(activeScheme):null,ratings:{},plans:modality==='image'?imagePlans(imageCount,prompt):modality==='code'?codePlans(imageCount,prompt):(isC2C?c2cPlans(activeScheme,prompt):makePlans(selected,catalog,prompt)).map(p=>({...p,text:'',status:'waiting'})),date:new Date().toLocaleString('zh-CN'),vote:null,notes:'',checks:[]};
  const r=appendConversationTurn(previous,turn);
  commitConversation(r);setDraft('');attachments.clear();setNotes('');
  if(modality==='image'||modality==='code'){setFinished(turn.plans.length);requestAnimationFrame(()=>latestTurn.current?.scrollIntoView({block:'start',behavior:'instant'}));return}
  setBusy(true);setFinished(0);
  startAnswers(r,{demo:isC2C||streamingPreview})
  requestAnimationFrame(()=>latestTurn.current?.scrollIntoView({block:'start',behavior:'instant'}));
 }
 function disposeStream(){
  const active=activeStream.current;if(!active)return;activeStream.current=null;
  active.controller.dispose();active.abort.abort();active.timers.forEach(clearTimeout);
  if(active.taskId)cancelCompare(active.taskId).catch(()=>{});
 }
 function stopAnswers(){const active=activeStream.current;if(!active)return;active.controller.stop();active.abort.abort();active.timers.forEach(clearTimeout);if(active.taskId)cancelCompare(active.taskId).catch(()=>{});activeStream.current=null}
 function startAnswers(conversation,{demo=false}={}){
  disposeStream();const turn=conversation.turns.at(-1),modelIds=turn.plans.map(p=>p.apiId||p.id||p.model);
  const active={abort:new AbortController(),timers:[],taskId:null};activeStream.current=active;setBusy(true);
  const valid=()=>activeStream.current===active&&currentRef.current?.id===conversation.id;
  active.controller=createAnswerStream({modelIds,reduced:()=>document.hidden||window.matchMedia('(prefers-reduced-motion: reduce)').matches,
   onUpdate:snapshots=>{if(!valid())return;const live=currentRef.current,existing=live.turns.find(t=>t.id===turn.id);if(!existing)return;
    const terminalChanged=snapshots.some((s,i)=>['done','error','stopped'].includes(s.status)&&existing.plans[i].status!==s.status);
    const next=updateConversationTurn(live,turn.id,{plans:existing.plans.map((p,i)=>({...p,...snapshots[i]}))});
    if(terminalChanged)commitConversation(next);else{currentRef.current=next;setCurrent(next)}
   },onSettled:()=>{if(valid()){setBusy(false);activeStream.current=null}}
  });
  if(demo){modelIds.forEach((id,i)=>{active.timers.push(setTimeout(()=>{if(!valid())return;active.controller.push(id,answerMarkdown(CONTENT[turn.kind][i%3]));active.controller.end(id,{source:'demo'})},350+i*300))});return}
  createCompare({question:questionWithAttachments(turn.question,turn.attachments),systemPrompt:turn.plans[0]?.prompt||'',modelIds},{signal:active.abort.signal})
   .then(async({taskId})=>{if(!valid()){cancelCompare(taskId).catch(()=>{});return}active.taskId=taskId;
    await streamCompare(taskId,{
     onChunk:({modelId,delta})=>{if(valid())active.controller.push(modelId,delta)},
     onDone:data=>{if(valid())active.controller.end(data.modelId,data)},
     onError:data=>{if(!valid())return;const error=data?.error?.message||'生成失败';if(data?.modelId)active.controller.end(data.modelId,{error});else active.controller.fail(error)}
    },{signal:active.abort.signal});
    if(valid())active.controller.fail('连接提前结束，未收到完成状态');
   }).catch(err=>{if(valid()&&err.name!=='AbortError')active.controller.fail(err?.message||'连接失败，请检查服务后重试')});
 }
 function stop(){stopAnswers();setBusy(false);setFinished(current?.plans.length||0);message.info('已停止生成，保留已收到的内容')}
 function vote(v,turn=current.turns.at(-1)){patchTurn(turn.id,bulkFeedbackPatch(turn,v));message.success(v==='both'?'已记录：全部都好':v==='neither'?'已记录：都需要改进':`已记录：${turn.plans[LETTERS.indexOf(v)].model} 更好`)}
 const rateAnswer=(turn,index,value)=>patchTurn(turn.id,feedbackPatch(turn,index,value));
 function toggleModel(id,checked){if(checked&&selected.length>=9){message.warning('最多同时比较 9 个模型，请先取消一个');return}if(!checked&&selected.length<=2){message.warning('至少保留 2 个模型');return}saveSelection(checked?[...selected,id]:selected.filter(x=>x!==id))}
 function setCount(n){saveSelection([...selected,...catalog.map(m=>m.id).filter(id=>!selected.includes(id))].slice(0,n))}
 function saveModel(){if(!editing.name.trim()||!editing.apiId.trim()){message.warning('请填写模型名称和模型 ID');return}const m={...editing,name:editing.name.trim(),apiId:editing.apiId.trim(),provider:editing.provider.trim()||'自定义'};const next=catalog.some(x=>x.id===m.id)?catalog.map(x=>x.id===m.id?m:x):[...catalog,m];setCatalog(next);store('arena-models-v2',next);setPanel(null);message.success('已保存演示配置')}
 function exportRecord(onlyTurn){if(!current)return;const turns=onlyTurn?.plans?[onlyTurn]:current.turns;const rows=[['数据类型','轮次','问题','对比方式','协作方案','方案','模型或方式','提供信息的模型','最终回答的模型','Fuser','系统提示词','回答','耗时类型','耗时秒','评分(1-5)','单项备注','偏好','单项评价','本轮备注','附件材料'],...turns.flatMap(turn=>turn.plans.map((p,i)=>['预置演示 · 非真实模型结果',current.turns.findIndex(t=>t.id===turn.id)+1,turn.question,turn.compareMode==='c2c'?'C2C 协作对比':'多模型对比',turn.scheme?.name||'',LETTERS[i],p.model,p.sharer||'',p.receiver||'',p.fuser||'',p.prompt,JSON.stringify(dataFor(i,turn)),'示例耗时（非实测）',p.seconds??(2.1+i*.6).toFixed(1),turn.ratings?.[i]?.score??'',turn.ratings?.[i]?.note||'',turn.vote||'未评价',feedbackText(modelFeedback(turn,i)),turn.id===current.turns.at(-1).id?notes:turn.notes,attachmentText(turn.attachments)]))];const a=document.createElement('a');const u=URL.createObjectURL(new Blob([csvText(rows)],{type:'text/csv;charset=utf-8'}));a.href=u;a.download=onlyTurn?.plans?'对照-本轮评价.csv':'对照-话题记录.csv';a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)}
 function voteLabel(turn){if(!turn.vote)return turn.plans.some((_,i)=>modelFeedback(turn,i))?'已作单项评价，未选择整体偏好':'未选择';if(turn.vote==='both')return '全部都好';if(turn.vote==='neither')return '都需改进';const i=LETTERS.indexOf(turn.vote);return i>=0?LETTERS[i]+' · '+turn.plans[i]?.model:turn.vote}
 function buildAnalysis(turn){const L=[];const entries=turn.plans.map((p,i)=>({name:p.model,d:dataFor(i,turn),r:turn.ratings?.[String(i)]||{},feedback:modelFeedback(turn,i)}));L.push('**各方案评价（用户评分与备注）**','');entries.forEach((e,i)=>{L.push(`- **${LETTERS[i]} ${e.name}**：${feedbackText(e.feedback)}；评分 ${e.r.score?e.r.score+'/5':'未评分'}；${e.r.note?'备注：'+e.r.note:'用户未填写备注，无法提取具体优点/不足'}。`)});L.push('');L.push('**关键差异（回答结构）**','');entries.forEach((e,i)=>{if(e.d.type==='image'){L.push(`- ${LETTERS[i]} ${e.name}：图片演示（${e.d.description.slice(0,24)}…）`)}else if(e.d.type==='code'){L.push(`- ${LETTERS[i]} ${e.name}：${e.d.title}（${e.d.lang}）代码演示`)}else if(e.d.type==='streamed'){L.push(`- ${LETTERS[i]} ${e.name}：流式文本回答（约 ${e.d.text.length} 字）`)}else{const n=(e.d.sections||[]).reduce((s,sec)=>s+sec[1].length,0);L.push(`- ${LETTERS[i]} ${e.name}：主题「${e.d.lead}」；覆盖 ${(e.d.sections||[]).length} 个部分、共 ${n} 条要点。`)}});L.push('');L.push('**推荐结论**','');if(turn.vote==='both'){L.push('用户认为所有方案都满足预期，可结合场景选用，本任务不强制二选一。依据：用户偏好选择「都好」。')}else if(turn.vote==='neither'){L.push('用户认为所有方案都需改进，本任务暂不推荐任一方案。依据：用户偏好选择「都不好」。建议补充需求或调整提示词后重新对比。')}else if(turn.vote){const i=LETTERS.indexOf(turn.vote);if(i>=0){const e=entries[i];L.push(`推荐 **${e.name}**。依据：用户偏好选择 ${LETTERS[i]}${e.r.score?'，评分 '+e.r.score+'/5':''}${e.r.note?'，备注：'+e.r.note:''}。`)}else{L.push('用户已作出偏好选择，请以「用户评价」区为准。')}}else{L.push(entries.some(e=>e.feedback||e.r.score)?'已记录各方案评价，尚无唯一偏好方案。请结合评分与备注选择。':'用户尚未评分或作出偏好选择，暂无推荐结论。依据：缺少用户评价数据。')}return L}
 function buildReport(turn){const L=[];L.push('# 对照 · 模型对比报告','');L.push(`- 问题：${turn.question}`);L.push(`- 对比方式：${turn.compareMode==='c2c'?'C2C 协作对比（3 种方式）':'多模型对比（'+turn.plans.length+' 个模型）'}`);L.push(`- 共同提示词：${turn.plans[0]?.prompt||'（未设置）'}`);L.push(`- 生成时间：${new Date().toLocaleString('zh-CN')}`);L.push(`- 数据说明：预置演示 · 非真实模型结果`,'');if(turn.attachments?.length)L.push('## 附件材料','',attachmentText(turn.attachments),'');L.push('## 一、模型回答','');turn.plans.forEach((p,i)=>{const d=dataFor(i,turn),r=turn.ratings?.[String(i)]||{};L.push(`### ${LETTERS[i]} · ${p.model}`,`- 单项评价：${feedbackText(modelFeedback(turn,i))}`,`- 评分：${r.score?r.score+' 分':'未评分'}`,`- 备注：${r.note||'未填写'}`,'**完整回答：**');if(d.type==='image'){L.push(`（图片演示 · ${d.description}）`)}else if(d.type==='code'){L.push('```'+d.lang+'\n'+d.code+'\n```')}else if(d.type==='streamed'){L.push(d.text)}else{L.push(d.lead,'',d.intro,'');(d.sections||[]).forEach(([t,items])=>{L.push(`**${t}**`);items.forEach(x=>L.push(`- ${x}`));L.push('')});L.push(`_${d.end}_`)}L.push('')});L.push('## 二、用户评价','',`- 偏好选择：${voteLabel(turn)}`,'- 评分与备注：见上方各方案「评分 / 备注」字段（未填写处已如实标注）','');L.push('## 三、对比分析（系统生成 · 仅针对本次任务）','');buildAnalysis(turn).forEach(x=>L.push(x));L.push('','---','*本报告由前端演示生成：回答为预置示例，不代表模型真实能力；对比分析为系统基于示例回答结构与用户评分/备注归纳，不构成选型结论。*');return L.join('\n')}
 function exportReport(){if(exporting||!current)return;const turn=current.turns.at(-1);setExporting(true);setTimeout(()=>{try{const text=buildReport(turn);const blob=new Blob([text],{type:'text/markdown;charset=utf-8'});const a=document.createElement('a');const u=URL.createObjectURL(blob);a.href=u;a.download='对照-对比报告-'+Date.now()+'.md';document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),1000);message.success('报告已生成并下载')}catch(err){message.error('报告生成失败：'+(err?.message||'未知错误')+'，请重试')}finally{setExporting(false)}},600)}
 const reportMenu={items:[{key:'csv',label:'导出 CSV（数据表）',icon:<FileTextIcon size={15}/>},{key:'md',label:'导出 MD 报告（含对比分析）',icon:<DownloadIcon size={15}/>}],onClick:({key})=>{if(key==='csv'){exportRecord(current.turns.at(-1))}else{exportReport()}}};
 async function copy(i,turn=current){const d=dataFor(i,turn);try{await navigator.clipboard.writeText(d.type==='streamed'?d.text:d.type==='code'?d.code:[d.lead,d.intro,...d.sections.flatMap(([t,a])=>[t,...a]),d.end].join('\n'));message.success(d.type==='streamed'?'已复制回答':d.type==='code'?'已复制示例代码':'已复制示例回答')}catch{message.info('请展开回答后选中文字复制')}}
 const categories=['全部模型','通用对话','深度推理','快速响应','长文本'];
 const filtered=catalog.filter(m=>(category==='全部模型'||m.category===category)&&(view==='all'||selected.includes(m.id))&&(m.name+m.provider+m.apiId).toLowerCase().includes(modelQuery.toLowerCase()));
 const columns=[
  {title:'参与对比',key:'selected',width:88,render:(_,m)=><Checkbox aria-label={'选择 '+m.name} checked={selected.includes(m.id)} onChange={e=>toggleModel(m.id,e.target.checked)}/>},
  {title:'模型',key:'model',width:250,render:(_,m)=><div className="catalog-model"><span className="catalog-avatar">{m.name.slice(0,1)}</span><div><strong>{m.name}</strong><small>{m.provider} · 示例名称</small></div></div>},
  {title:'模型 ID',dataIndex:'apiId',width:220,render:s=><code className="model-id">{s}</code>},
  {title:'用途',dataIndex:'category',width:115},
  {title:'连接状态',key:'status',width:125,render:()=> <span className="table-status"><i/>待接入</span>},
  {title:'操作',key:'action',width:88,fixed:'right',render:(_,m)=><button className="table-edit" onClick={()=>{setEditing({...m});setPanel('modelEdit')}}>编辑</button>}
 ];
 const composer=<div className="composer-wrap"><ComposerBeam appearance={appearance}><ComposerSurface attachments={attachments} disabled={busy}><label htmlFor="question" className="sr-only">输入对比问题</label><Input.TextArea ref={input} id="question" value={draft} onChange={e=>setDraft(e.target.value)} placeholder={modality==='image'?'描述你想要的图片，如主体、风格、光线与构图…':modality==='code'?'描述你想要的代码，如功能、输入输出与边界…':modality==='video'?'描述你想要的视频，如场景、动作与镜头运动…':current?'继续追问，保留在当前话题中…':isC2C?'输入问题，比较单模型、文字协作与缓存协作…':`输入一段提示词，让 ${selected.length} 个模型同时回答…`} autoSize={{minRows:2,maxRows:5}} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey&&!e.nativeEvent.isComposing){e.preventDefault();run()}}} disabled={busy}/><div className="composer-toolbar"><div className="composer-options"><AttachMenu attachments={attachments} disabled={busy}/>
 {modality==='text'&&<Dropdown trigger={['click']} placement="topLeft" menu={{selectedKeys:[compareMode],items:[{key:'models',label:'多模型对比'},{key:'c2c',label:'C2C 协作对比'}],onClick:({key})=>setCompareMode(key)}}><button className="compare-mode-button" disabled={busy} aria-label="选择对比方式">{isC2C?'C2C 协作对比':'多模型对比'}<ChevronDownIcon size={12}/></button></Dropdown>}
 {isC2C?<button className="model-count-button" onClick={()=>{setModelTab('c2c');showModels()}} disabled={busy}><ArrowLeftRightIcon size={16}/>3 种方式<ChevronDownIcon size={12}/></button>:(modality==='image'||modality==='code')?<Dropdown trigger={['click']} placement="topLeft" menu={{selectedKeys:[String(imageCount)],onClick:({key})=>setImageCount(Number(key)),items:Array.from({length:8},(_,i)=>({key:String(i+2),label:(i+2)+' 个示例模型'}))}}><button className="model-count-button" disabled={busy} aria-label="选择图片对比模型数量"><ArrowLeftRightIcon size={16}/>{imageCount} 个模型<ChevronDownIcon size={12}/></button></Dropdown>:<button className="model-count-button" onClick={showModels} disabled={busy||modality==='video'}><ArrowLeftRightIcon size={16}/>{modality==='video'?'待配置模型':selected.length+' 个模型'}<ChevronDownIcon size={12}/></button>}
 <CompareTypeMenu value={modality} onChange={setModality} disabled={busy}/>
 </div><div className="composer-send"><button className="icon-btn config-btn" aria-label="编辑共同系统提示词" onClick={()=>setPanel('prompt')} disabled={busy}><SlidersHorizontalIcon size={18}/></button><Button className={'send-button '+(draft.trim()&&modality!=='video'?'ready':'')} aria-label={busy?'停止生成':modality==='video'?'视频模型待接入':current?'发送追问':'开始对比'} disabled={!busy&&(!draft.trim()||modality==='video')} onClick={busy?stop:run} icon={busy?<XIcon size={18}/>:<ArrowUpIcon size={18}/>}/></div></div>{isC2C&&<div className="c2c-composer-context"><span>协作方案</span><Select aria-label="本次协作方案" size="small" disabled={busy} value={activeScheme.id} onChange={selectScheme} options={schemes.map(s=>({value:s.id,label:s.name}))}/><span>服务未连接 · 演示模式</span></div>}</ComposerSurface></ComposerBeam>{current&&<p className="demo-footnote">{streamingPreview?'流式动效演示 · 预置内容，不调用模型，不保存历史':isC2C?'C2C 交互演示 · 回答与耗时均为预置示例，不代表真实协作效果':modality==='image'?'图片演示 · 发送后展示预置咖啡机图片，不随提示词改变，未接入 API':modality==='code'?'代码演示 · 发送后展示预置代码，未接入 API':modality==='video'?'视频模型尚未接入，暂不能生成视频；可切换文本或图片体验演示。':'模型独立流式生成 · 未配置密钥的模型使用预置演示回答'}</p>}</div>;
 return <div className={'arena-shell '+(collapsed?'is-collapsed':'')} style={{'--composer-height':composerH+'px'}}>
  <a className="skip-link" href="#main" onClick={e=>{e.preventDefault();const main=document.getElementById('main');if(main){main.tabIndex=-1;main.focus();main.scrollIntoView({block:'start'})}}}>跳到主要内容</a>
  <aside className={'sidebar '+(sidebar?'mobile-open':'')}>
   <div className="brand-row"><button className="wordmark" onClick={reset} aria-label="对照首页"><svg className="brand-logo" preserveAspectRatio="xMinYMid meet" viewBox={appearance==='dark'?'81 308 1614 230':'77 308 1622 230'} aria-hidden="true" focusable="false"><image href={appearance==='dark'?duizhaoLogoDark:duizhaoLogoLight} width="1774" height="887"/></svg></button><button className="icon-btn collapse" aria-label="收起侧栏" onClick={()=>window.innerWidth<760?setSidebar(false):setCollapsed(true)}><MenuIcon size={18}/></button></div>
   <nav className="primary-nav" aria-label="主导航"><MotionButton icon={PlusIcon} onClick={reset}>新建对比</MotionButton><MotionButton icon={SlidersHorizontalIcon} className={screen==='models'?'nav-selected':''} onClick={showModels}>模型配置<span className="nav-count">{selected.length}</span></MotionButton><MotionButton icon={BookOpenIcon} className={screen==='library'?'nav-selected':''} onClick={showLibrary}>我的题库</MotionButton><MotionButton icon={CheckCheckIcon} className={screen==='evaluations'?'nav-selected':''} onClick={()=>{setEvaluationSeed(null);showEvaluations()}}>测评任务</MotionButton><MotionButton icon={SearchIcon} onClick={()=>{setPanel('search');setSidebar(false)}}>搜索记录<kbd>⌘ K</kbd></MotionButton></nav>
   <div className="history"><div className="nav-label">最近的对比<span>{records.length}</span></div>{sortConversations(records).map(r=><div key={r.id} className={'history-row '+(current?.id===r.id&&screen==='arena'?'active':'')}>
    <button title={r.title} disabled={busy} className="history-item" onClick={()=>openRecord(r)}>{r.pinned?<PinIcon size={14}/>:<ArrowLeftRightIcon size={14}/>}<span>{r.title}</span>{r.vote&&<span className="history-dot"/>}</button>
    <Dropdown trigger={['click']} placement="bottomLeft" menu={{items:[{key:'pin',label:r.pinned?'取消置顶':'置顶',icon:<PinIcon size={15}/>},{key:'rename',label:'重命名',icon:<PencilIcon size={15}/>},{key:'delete',label:'删除',icon:<Trash2Icon size={15}/>,danger:true}],onClick:({key})=>topicAction(r,key)}}><button className="icon-btn history-more" disabled={busy} aria-label={'对话操作：'+r.title} aria-haspopup="menu"><EllipsisIcon size={18}/></button></Dropdown>
   </div>)}{!records.length&&<p className="history-empty">暂无对话，开始一次新的对比。</p>}<div className="side-hint">让每一次比较，都有据可循。</div></div>
   <div className="sidebar-bottom"><MotionButton icon={SettingsIcon} onClick={()=>{setPanel('settings');setSidebar(false)}}>连接设置<span className="not-connected">未连接</span></MotionButton><div className="workspace"><span className="avatar">PM</span><div><strong>个人工作空间</strong></div><span className="status-dot"/></div></div>
  </aside>{sidebar&&<button className="side-overlay" aria-label="关闭导航" onClick={()=>setSidebar(false)}/>}
  <div className="main-shell"><header className={'topbar '+(screen!=='arena'?'config-topbar':!current?'home-topbar':'')}><div className="topbar-left"><button className="icon-btn open-nav" aria-label="打开导航" onClick={()=>window.innerWidth<760?setSidebar(true):setCollapsed(false)}><MenuIcon size={20}/></button>{(screen!=='arena'||current)&&<span className="page-title">{screen==='models'?'模型配置':screen==='library'?'我的题库':screen==='evaluations'?'测评任务':current.title}</span>}</div><div className="topbar-right"><MotionButton icon={appearance==='dark'?SunIcon:MoonIcon} size={17} className="theme-toggle" aria-label={appearance==='dark'?'切换为浅色模式':'切换为深色模式'} title={appearance==='dark'?'切换为浅色模式':'切换为深色模式'} onClick={onAppearanceChange}><span>{appearance==='dark'?'浅色':'深色'}</span></MotionButton>{current&&screen==='arena'&&<button className="icon-btn" aria-label="导出本次记录" onClick={exportRecord}><DownloadIcon size={17}/></button>}</div></header>
  {screen==='evaluations'?<Evaluations tasks={evaluationTasks} onSave={saveEvaluationTasks} library={library} models={catalog} selected={selected} seed={evaluationSeed} onClearSeed={()=>setEvaluationSeed(null)}/>:screen==='library'?<PromptLibrary items={library} onSave={saveLibrary} onUse={useLibraryPrompt} defaultPrompt={DEFAULT_PROMPT}/>:screen==='models'?<><div className="model-workspace-tabs" role="tablist" aria-label="模型配置类型"><button role="tab" aria-selected={modelTab==='models'} onClick={()=>setModelTab('models')}>云端 API 模型</button><button role="tab" aria-selected={modelTab==='c2c'} onClick={()=>setModelTab('c2c')}>C2C 协作方案</button></div>{modelTab==='c2c'?<C2CSchemes schemes={schemes} selectedId={activeScheme.id} onSave={saveSchemes} onUse={useScheme} onSettings={showC2CSettings}/>:<main id="main" className="models-page">
   <aside className="model-filters" aria-label="模型筛选"><div className="filter-group"><h3>显示范围</h3><Segmented aria-label="显示范围" block value={view} onChange={setView} options={[{label:'全部',value:'all'},{label:'已选',value:'selected'}]}/></div><div className="filter-group"><h3>模型用途 <span>{categories.length-1}</span></h3>{categories.map(c=><button key={c} onClick={()=>setCategory(c)} className={'filter-item '+(c===category?'active':'')}><span>{c}</span>{c===category?<CheckIcon size={16}/>:<small>{catalog.filter(m=>m.category===c).length}</small>}</button>)}</div><div className="filter-group"><h3>调用方式</h3><div className="filter-static"><span className="radio-dot"/>云端 API</div><p>使用已配置的模型服务，<br/>电脑无需安装模型。</p></div><div className="filter-tip"><span>本次对比</span><strong>{selected.length}<small> / 9 个模型</small></strong><p>所有模型使用同一段提示词，<br/>名称直接展示，无需盲选。</p></div></aside>
   <section className="model-main"><div className="model-heading"><div><h1>我的模型 <span>Model workspace</span></h1><p>选好模型，同一个问题，一起比较。</p></div><Button icon={<PlusIcon size={16}/>} onClick={()=>{setEditing({id:'m'+Date.now(),name:'',provider:'自定义',category:'通用对话',apiId:''});setPanel('modelEdit')}}>添加模型</Button></div><div className="model-summary"><span>{catalog.length} 个模型配置</span><span className="green-text">{selected.length} 个参与对比</span><span>默认 2 个 · 最多 9 个</span><Button className="connection-settings-button" onClick={()=>setPanel('settings')}>连接设置</Button></div>
   <div className="model-toolbar"><div className="count-setting"><label htmlFor="model-count">对比数量</label><Select id="model-count" aria-label="对比模型数量" value={selected.length} onChange={setCount} options={Array.from({length:8},(_,i)=>({value:i+2,label:(i+2)+' 个模型'}))}/></div><Input aria-label="搜索模型" prefix={<SearchIcon size={16}/>} value={modelQuery} onChange={e=>setModelQuery(e.target.value)} placeholder="搜索模型、厂商或 ID" allowClear/></div>
   <Table className="model-table" rowKey="id" columns={columns} dataSource={filtered} pagination={false} scroll={{x:886}} rowClassName={m=>selected.includes(m.id)?'model-row-selected':''} locale={{emptyText:'没有匹配的模型，请调整筛选条件'}}/>
   <div className="selection-tray"><div className="selected-models-label">已选 {selected.length} 个</div><div className="selected-chips">{selected.map(id=><span key={id}>{catalog.find(m=>m.id===id)?.name}</span>)}</div></div>
   <div className="config-bottom"><Button className="edit-prompt-button" icon={<FileTextIcon size={16}/>} onClick={()=>setPanel('prompt')}>编辑提示词</Button><Button type="primary" onClick={()=>{setCompareMode('models');setModality('text');returnArena();message.success(`下一次对比将使用 ${selected.length} 个模型`)}}>使用这 {selected.length} 个模型 <ArrowRightIcon size={16}/></Button></div>

   </section>
  </main>}</>:<><main id="main" className={current?'comparison-page':'home-page'}>
   {!current?<div className="welcome"><h1>今天，想比较什么？</h1><p className="welcome-sub">同一段提示词，看看哪种回答更适合你。</p>{composer}{modality==='text'?<div className="starters"><div className="starters-label">案例</div><div className="starter-grid">{homePrompts(library).map(t=><button key={t.id} className="starter" onClick={()=>choose(t)}><span className="starter-icon"><PromptIcon name={t.icon}/></span><span><strong>{t.title}</strong><small>{t.desc}</small></span></button>)}</div></div>:modality==='image'?<div className="media-starter"><span>从一个图片案例开始</span><button onClick={()=>{setDraft(IMAGE_PROMPT);input.current?.focus()}}><ImageIcon size={19}/><span><strong>奶油白咖啡机 · 产品宣传图</strong><small>填入示例提示词，再点击发送查看两种画面</small></span><ArrowRightIcon size={17}/></button></div>:modality==='code'?<div className="media-starter"><span>从一个代码案例开始</span><button onClick={()=>{setDraft(CODE_PROMPT);input.current?.focus()}}><CodeIcon size={19}/><span><strong>数组求和 · JavaScript 函数</strong><small>填入示例提示词，再点击发送查看两种实现</small></span><ArrowRightIcon size={17}/></button></div>:<div className="video-mode-note"><VideoIcon size={20}/><div><strong>视频对比</strong><p>在这里描述视频，接入后可在当前话题中比较各模型的结果。</p></div></div>}</div>:<>
   {current.turns.map((turn,index)=>{const isLatest=index===current.turns.length-1,turnBusy=busy&&isLatest;return <section key={turn.id} className="conversation-turn" aria-label={'第 '+(index+1)+' 轮对话'} ref={isLatest?latestTurn:null}><div className="turn-label">第 {index+1} 轮 · {turn.compareMode==='c2c'?'C2C 协作对比':turn.modality==='image'?'图片':turn.modality==='code'?'代码':'文本'}</div>
   <div className="question-bubble">{turn.question}{turn.attachments?.length>0&&<AttachmentList items={turn.attachments}/>}</div>
   {turn.compareMode==='c2c'&&<div className="c2c-turn-context"><strong>{turn.scheme.name}</strong><br/>提供信息：{turn.scheme.sharer} → 最终回答：{turn.scheme.receiver}<br/>Fuser：{turn.scheme.fuser} · 本轮配置快照</div>}
   {turn.modality==='image'?<ImageAnswers turn={turn} onFeedback={(index,value)=>rateAnswer(turn,index,value)} disabled={busy}/>:turn.modality==='code'?<CodeAnswers turn={turn} onFeedback={(index,value)=>rateAnswer(turn,index,value)} disabled={busy}/>:<div className={'answer-grid '+(turn.compareMode==='c2c'?'c2c-grid':turn.plans.length>2?'multi-models':'')} aria-busy={turnBusy}>{turn.plans.map((p,i)=>{const label=LETTERS[i],feedback=modelFeedback(turn,i),win=feedback==='better',neither=feedback==='worse',d=dataFor(i,turn),streamed=d.type==='streamed',ready=streamed?['done','error','stopped'].includes(d.status):(!turnBusy||i<finished),canRate=ready&&(!streamed||d.status==='done');return <ProCard key={label} className={'answer-card '+(win?'winner':neither?'neither':'')} bordered><div className="answer-card-header"><span className="model-label"><ModelStatus ready={ready} label={label} appearance={appearance}/><span className="model-name" title={p.model}>{p.model}</span>{win&&<CheckCheckIcon size={15}/>}{neither&&<XIcon size={15}/>}</span><div className="card-tools"><button className="icon-btn" aria-label={'复制 '+p.model+' 回答'} onClick={()=>copy(i,turn)} disabled={!ready}><CopyIcon size={15}/></button><button className="icon-btn" aria-label={'展开 '+p.model+' 回答'} onClick={()=>setExpanded({turn,index:i})} disabled={!ready}><svg width="15" height="15" viewBox="0 0 20 20" fill="none" stroke="currentColor" strokeWidth="1.5" aria-hidden="true"><path d="M7 3H3v4m10-4h4v4M3 13v4h4m10-4v4h-4"/></svg></button></div></div>{turn.compareMode==='c2c'&&<div className="c2c-method-desc">{p.description}</div>}<div className="answer-scroll">{streamed?<div className="answer-copy"><StreamedAnswer text={d.text} status={d.status} error={d.error} loading={<div className="answer-loading" role="status"><TextShimmer duration={2.4} className="answer-loading-message">正在为您生成中…</TextShimmer></div>}/></div>:!ready?<div className="answer-copy answer-loading" role="status"><TextShimmer duration={2.4} className="answer-loading-message">正在为您生成中…</TextShimmer></div>:<div className="answer-copy"><Answer data={d}/></div>}</div><div className="answer-card-footer"><span>{ready?(streamed?(d.status==='error'?'生成失败':d.status==='stopped'?'已停止':d.source==='demo'?'演示完成 · 非实测':'生成完成'):`耗时 ${p.seconds??(2.1+i*.6).toFixed(1)} 秒 · 非实测`):'生成中…'}</span><span role="status" className="sr-only">{p.model}：{ready?(canRate?'生成完成，可评价':'生成已结束'):'生成中'}</span>{canRate&&<AnswerFeedback value={feedback} label={label} model={p.model} disabled={false} onChange={value=>rateAnswer(turn,i,value)}/>}</div></ProCard>})}</div>}
   <ResultReview turn={turn} disabled={busy} onChange={ratings=>patchTurn(turn.id,{ratings})}/><div className="turn-evaluation-link"><Button disabled={busy} onClick={()=>evaluateTurn(turn)}>用本轮建立测评任务</Button></div></section>})}</>}

  </main>{current&&<div className="bottom-dock" ref={footer}><div className="vote-bar" aria-label="回答偏好">{current.plans.length===2?<><button disabled={busy} className={current.vote==='A'?'selected':''} onClick={()=>vote('A')}>← {current.plans[0].model}</button><button disabled={busy} className={current.vote==='both'?'selected':''} onClick={()=>vote('both')}>都好</button><button disabled={busy} className={current.vote==='neither'?'selected neither':''} onClick={()=>vote('neither')}>都不好</button><button disabled={busy} className={current.vote==='B'?'selected':''} onClick={()=>vote('B')}>{current.plans[1].model} →</button><Dropdown trigger={['click']} placement="top" menu={reportMenu}><button disabled={exporting} className="report-btn">{exporting?<RefreshCwIcon size={14} className="spin"/>:<DownloadIcon size={14}/>}{exporting?'正在生成报告…':'导出报告'}<ChevronDownIcon size={12}/></button></Dropdown></>:<><span className="multi-summary">{current.compareMode==='c2c'?'3 种回答方式':current.plans.length+' 个模型'} · {busy?'演示加载中':'回答已展示'}</span><button disabled={busy} onClick={()=>setPanel('evaluation')}>评价与备注</button><button disabled={busy} className={current.vote==='neither'?'selected neither':''} onClick={()=>vote('neither')}>都需改进</button><Dropdown trigger={['click']} placement="top" menu={reportMenu}><button disabled={exporting} className="report-btn">{exporting?<RefreshCwIcon size={14} className="spin"/>:<DownloadIcon size={14}/>}{exporting?'正在生成报告…':'导出报告'}<ChevronDownIcon size={12}/></button></Dropdown></>}</div>{composer}</div>}</>}
  </div>
  <Modal title="重命名对话" open={renameTarget!==null} onCancel={()=>setRenameTarget(null)} onOk={saveTopicTitle} okText="保存" cancelText="取消" destroyOnHidden afterOpenChange={open=>{if(open)document.getElementById('topic-title')?.select()}}>
   <Form layout="vertical"><Form.Item label="对话名称" htmlFor="topic-title"><Input id="topic-title" aria-label="对话名称" value={topicTitle} maxLength={80} showCount onChange={e=>setTopicTitle(e.target.value)} onPressEnter={saveTopicTitle}/></Form.Item></Form>
  </Modal>
  <Drawer open={!!panel} onClose={()=>setPanel(null)} title={{settings:'连接设置',search:'搜索对比记录',evaluation:'评价与备注',prompt:'共同系统提示词',modelEdit:editing&&catalog.some(m=>m.id===editing.id)?'编辑模型':'添加模型'}[panel]} size={520}>
   {panel==='settings'&&<div className="connection-tabs"><Segmented block aria-label="连接类型" value={connectionTab} onChange={setConnectionTab} options={[{value:'maas',label:'模型 API'},{value:'c2c',label:'C2C 服务'}]}/></div>}
   {panel==='settings'&&connectionTab==='c2c'&&<C2CConnection value={c2cConnection} onSave={value=>{setC2cConnection(value);store('arena-c2c-connection',value)}}/>}
   {panel==='settings'&&connectionTab==='maas'&&<><div className="connection-status"><span className="connection-dot"/><div><strong>{backendKeys.some(k=>k.configured)?'已配置密钥':'尚未配置密钥'}</strong><p>密钥保存在后端，浏览器不保存明文。</p></div></div><Form layout="vertical"><Form.Item label="连接名称"><Input value={connection} onChange={e=>setConnection(e.target.value)}/></Form.Item><Form.Item label="服务地址"><Input value={url} onChange={e=>setUrl(e.target.value)}/></Form.Item>{backendKeys.map(k=><Form.Item key={k.ref} label={k.label+' API Key'} extra={k.configured?'已配置 · 输入新值可替换':'未配置'}><Input.Password placeholder="粘贴该平台 API Key" value={keyDraft[k.ref]||''} onChange={e=>setKeyDraft({...keyDraft,[k.ref]:e.target.value})}/></Form.Item>)}</Form><Button type="primary" block onClick={saveKeys} loading={savingKeys}>保存密钥</Button><p className="drawer-intro">密钥只发送到后端保存，浏览器不回显完整密钥。保存后可真实调用对应模型。</p><Button block onClick={showModels}>管理模型列表</Button></>}
   {panel==='modelEdit'&&editing&&<><p className="drawer-intro">模型名称会直接显示在回答顶部。请根据服务商控制台填写模型 ID；当前不验证可用性。</p><Form layout="vertical"><Form.Item label="显示名称" required><Input aria-label="模型显示名称" value={editing.name} onChange={e=>setEditing({...editing,name:e.target.value})}/></Form.Item><Form.Item label="模型 ID" required><Input aria-label="模型 API ID" value={editing.apiId} onChange={e=>setEditing({...editing,apiId:e.target.value})}/></Form.Item><Form.Item label="厂商"><Input value={editing.provider} onChange={e=>setEditing({...editing,provider:e.target.value})}/></Form.Item><Form.Item label="用途"><Select value={editing.category} options={categories.slice(1).map(c=>({value:c,label:c}))} onChange={category=>setEditing({...editing,category})}/></Form.Item><Button block type="primary" onClick={saveModel}>保存模型配置</Button></Form></>}
   {panel==='prompt'&&<><p className="drawer-intro">这里设置所有模型共同遵守的要求；输入框中的问题也会原样发给所有已选模型。</p><Input.TextArea aria-label="共同系统提示词" rows={8} value={prompt} onChange={e=>{setPrompt(e.target.value);store('arena-prompt-v2',e.target.value)}}/><p className="muted">配置影响下一次对比，历史记录保留原来的提示词。</p><Button block type="primary" onClick={()=>{setPanel(null);message.success('共同提示词已保存')}}>完成</Button></>}
   {panel==='search'&&<><Input className="soft-focus-field" aria-label="搜索记录关键词" autoFocus prefix={<SearchIcon size={17}/>} value={search} onChange={e=>setSearch(e.target.value)} placeholder="搜索问题或记录名称" allowClear/><div className="search-results">{records.filter(r=>(r.title+r.turns.map(t=>t.question).join(' ')).includes(search)).map(r=><button className="search-row" key={r.id} disabled={busy} onClick={()=>openRecord(r)}><HistoryIcon size={18}/><div><strong>{r.title}</strong><small>{r.date} · {r.turns.length} 轮对话 · {r.plans.length} 个模型</small></div><ArrowRightIcon size={16}/></button>)}{!records.some(r=>(r.title+r.turns.map(t=>t.question).join(' ')).includes(search))&&<div className="empty-state">没有找到相关记录<br/><small>试试更短的关键词</small></div>}</div></>}
   {panel==='evaluation'&&current&&<><p className="drawer-intro">先写下判断依据，再决定偏好。这里的评价只对应预置示例。</p><div className="review-checks">{(current.modality==='image'?['是否符合提示词描述？','产品细节是否自然？','构图与光影是否合适？']:current.modality==='code'?['代码是否正确？','边界情况是否覆盖？','可读性与命名是否清晰？']:['业务规则是否完整？','异常情况是否遗漏？','验收标准是否可验证？']).map((x,i)=><label key={current.id+x}><input type="checkbox" defaultChecked={current.checks?.includes(i)} onChange={e=>{const checks=new Set(current.checks||[]);e.target.checked?checks.add(i):checks.delete(i);saveCurrent({...current,checks:[...checks]})}}/>{x}</label>)}</div><Form layout="vertical"><Form.Item label="更符合需求的回答"><Select aria-label="偏好模型" value={current.vote} placeholder="选择你的偏好" onChange={v=>vote(v)} options={[...current.plans.map((p,i)=>({value:LETTERS[i],label:p.model})),{value:'both',label:'全部都好'},{value:'neither',label:'都需改进'}]}/></Form.Item><Form.Item label="评价备注"><Input.TextArea value={notes} onChange={e=>setNotes(e.target.value)} rows={5} placeholder="记录哪部分更完整，以及还有什么需要改进。"/></Form.Item><Button type="primary" block onClick={()=>{saveCurrent({...current,notes});message.success('评价已保存');setPanel(null)}}>保存评价</Button></Form></>}
  </Drawer><Drawer open={expanded!==null} onClose={()=>setExpanded(null)} title={expanded?expanded.turn.plans[expanded.index].model+' · 演示回答':''} size={720}>{expanded!==null&&current&&<div className="answer-copy expanded">{dataFor(expanded.index,expanded.turn).type==='streamed'?<StreamedAnswer status="done" text={dataFor(expanded.index,expanded.turn).text}/>:<Answer data={dataFor(expanded.index,expanded.turn)}/>}</div>}</Drawer>
 </div>
}
function ArenaApp(){
 const [appearance,setAppearance]=useState(()=>read('arena-appearance','dark')==='light'?'light':'dark');
 const light=appearance==='light';
 useEffect(()=>{document.documentElement.dataset.theme=appearance;try{localStorage.setItem('arena-appearance',JSON.stringify(appearance))}catch{}},[appearance]);
 const colors=light?{base:'#f7f6f2',panel:'#ffffff',text:'#2b2c25',secondary:'#686155',border:'#d7d3c9',green:'#287b42',drawer:'#faf9f6',elevated:'#ffffff',header:'#eeece6',hover:'#f2f5ed',track:'#eeece6',selected:'#ffffff'}:{base:'#242320',panel:'#2b2a27',text:'#e6e3dd',secondary:'#aaa59a',border:'#49463f',green:'#65bf79',drawer:'#282723',elevated:'#302e2a',header:'#2d2b27',hover:'#34332c',track:'#2e2c27',selected:'#1e1d19'};
 return <ConfigProvider theme={{algorithm:light?theme.defaultAlgorithm:theme.darkAlgorithm,token:{colorPrimary:colors.green,colorBgBase:colors.base,colorBgContainer:colors.panel,colorText:colors.text,colorTextSecondary:colors.secondary,colorTextPlaceholder:colors.secondary,colorBorder:colors.border,borderRadius:8,fontSize:14,controlHeight:38,fontFamily:'-apple-system,BlinkMacSystemFont,"PingFang SC","Microsoft YaHei",sans-serif'},components:{Button:{primaryShadow:'none',colorPrimary:light?'#287b42':'#6dc580',colorTextLightSolid:light?'#ffffff':'#132218'},Drawer:{colorBgElevated:colors.drawer},Select:{colorBgElevated:colors.elevated},Table:{headerBg:colors.header,rowHoverBg:colors.hover,borderColor:colors.border,headerColor:colors.secondary,cellPaddingBlock:17},Segmented:{trackBg:colors.track,itemSelectedBg:colors.selected}}}}><AntApp><Workspace appearance={appearance} onAppearanceChange={()=>setAppearance(v=>v==='dark'?'light':'dark')}/></AntApp></ConfigProvider>
}
createRoot(document.getElementById('root')).render(<ArenaApp/>);
