import React,{useState} from 'react';
import {Button,Input,Form,Select,Drawer,App as AntApp} from 'antd';
import {ArrowRightIcon,PlusIcon,CheckIcon} from '@animateicons/react/lucide';
import {C2C_PAIRS,checkServiceUrl} from './c2c.mjs';
import './c2c.css';
export function C2CConnection({value,onSave}){
 const [address,setAddress]=useState(value.address||'');const [result,setResult]=useState(null);const {message}=AntApp.useApp();
 function validate(){const error=checkServiceUrl(address);setResult(error?{error,text:error}:{error:false,text:'地址格式正确。当前 HTML 尚未接入连接检测接口，无法确认服务是否可用。'});return !error;}
 return <><div className="connection-status"><span className="connection-dot"/><div><strong>C2C 服务未连接</strong><p>当前为交互演示，尚未请求真实后台。</p></div></div><Form layout="vertical"><Form.Item label="C2C 后台地址" extra="填写研发提供的服务地址。模型密钥由后台保管。" validateStatus={result?.error?'error':undefined} help={result?.error?result.text:undefined}><Input aria-label="C2C 后台地址" placeholder="https://c2c.example.com" value={address} onChange={e=>{setAddress(e.target.value);setResult(null)}}/></Form.Item><div className="c2c-actions"><Button onClick={validate}>测试连接</Button><Button type="primary" onClick={()=>{if(validate()){onSave({address:address.trim()});message.success('地址已保存，服务仍待接入')}}}>保存地址</Button></div></Form>{result&&!result.error&&<p role="status" className="c2c-feedback">{result.text}</p>}<div className="c2c-help"><h3>接入后会检查什么？</h3><p>服务能否访问、模型是否已加载，以及所选 Fuser 是否可用。</p><p>现在可以先保存地址，回到输入框体验三种回答方式的演示。</p></div></>;
}
export function C2CSchemes({schemes,selectedId,onSave,onUse,onSettings}){
 const [editing,setEditing]=useState(null);const {message}=AntApp.useApp();const pair=C2C_PAIRS.find(p=>p.id===editing?.pairId);
 function save(){if(!editing.name.trim()){message.warning('请填写方案名称');return}const item={...editing,name:editing.name.trim()};if(schemes.some(s=>s.id!==item.id&&s.name===item.name)){message.warning('方案名称已存在，请换一个名称');return}onSave(schemes.some(s=>s.id===item.id)?schemes.map(s=>s.id===item.id?item:s):[...schemes,item]);setEditing(null);message.success('协作方案已保存，实际可用性待服务验证');}
 return <main id="main" className="c2c-schemes"><div className="model-heading"><div><h1>C2C 协作方案</h1><p>配置一组模型，对比独立回答、文字协作和缓存协作。</p></div><Button icon={<PlusIcon size={16}/>} onClick={()=>setEditing({id:crypto.randomUUID(),name:'',pairId:'qwen-small'})}>新建协作方案</Button></div><div className="c2c-service-line"><span><i/>服务未连接 · 当前可体验预置演示</span><button className="plain-button" onClick={onSettings}>配置 C2C 服务 <ArrowRightIcon size={15}/></button></div><p className="drawer-intro">选择配套的模型组合，Fuser 随组合匹配。列表仅表示已保存的配置，不表示服务器已安装模型。</p><div className="c2c-scheme-list">{schemes.map(s=>{const p=C2C_PAIRS.find(p=>p.id===s.pairId);return <section className="c2c-scheme" key={s.id}><header><h2>{s.name}</h2><span>{s.id===selectedId?'当前方案':'已保存'} · 待验证</span></header><dl><div><dt>提供信息的模型</dt><dd>{p.sharer}</dd></div><div><dt>最终回答的模型</dt><dd>{p.receiver}</dd></div><div><dt>配套 Fuser</dt><dd>{p.fuser}</dd></div></dl><footer><button className="plain-button" onClick={()=>setEditing({...s})}>编辑方案</button><Button type={s.id===selectedId?'primary':'default'} onClick={()=>onUse(s.id)}>使用方案并对比 <ArrowRightIcon size={15}/></Button></footer></section>})}</div><Drawer open={!!editing} title="配置协作方案" onClose={()=>setEditing(null)} size={520}>{editing&&<Form layout="vertical"><Form.Item label="方案名称" required><Input aria-label="协作方案名称" maxLength={40} value={editing.name} onChange={e=>setEditing({...editing,name:e.target.value})} placeholder="例如：退款需求协作测试"/></Form.Item><Form.Item label="配套模型组合"><Select aria-label="配套模型组合" value={editing.pairId} onChange={pairId=>setEditing({...editing,pairId})} options={C2C_PAIRS.map(p=>({value:p.id,label:p.label}))}/></Form.Item><dl className="c2c-pair-details"><dt>提供信息的模型</dt><dd>{pair.sharer}</dd><dt>最终回答的模型</dt><dd>{pair.receiver}</dd><dt>匹配的 Fuser</dt><dd>{pair.fuser}</dd></dl><p className="drawer-intro">组合与 Fuser 一起保存，避免误配。这里不执行下载或训练。</p><Button type="primary" block onClick={save}>保存协作方案</Button></Form>}</Drawer></main>;
}
export function ResultReview({turn,onChange,disabled}){
 return <div className="result-review"><div className="result-review-heading"><strong>评分与备注</strong></div><div className={'review-grid '+(turn.compareMode==='c2c'?'c2c-grid':turn.plans.length>2?'multi-models':'')}>{turn.plans.map((p,i)=>{const key=String(i),rating=turn.ratings?.[key]||{};return <div className="review-item" key={p.id||i}><label htmlFor={'score-'+turn.id+'-'+i}><span className="model-letter">{'ABCDEFGHI'[i]}</span>{p.model}</label><Select id={'score-'+turn.id+'-'+i} aria-label={'ABCDEFGHI'[i]+' '+p.model+' 评分'} allowClear disabled={disabled} placeholder="未评分" value={rating.score} options={[1,2,3,4,5].map(n=>({value:n,label:n+' 分'}))} onChange={score=>onChange({...turn.ratings,[key]:{...rating,score}})}/><Input.TextArea aria-label={'ABCDEFGHI'[i]+' '+p.model+' 备注'} disabled={disabled} placeholder="具体哪里更好，哪里需要改进？" autoSize={{minRows:2,maxRows:4}} value={rating.note||''} onChange={e=>onChange({...turn.ratings,[key]:{...rating,note:e.target.value}})}/></div>})}</div></div>;
}
