import React,{useState} from 'react';
import {App,Button,Input,Checkbox} from 'antd';
import {MODULES,SCENARIOS,newRubric,caseCriteria,createTask,addExperiment,saveRun,retryRun,acceptanceStatus,qualityScore,summarize,modelSummaries,statusLabel,sourceLabel,detailCSV,summaryCSV,taskReport,rawPackage} from './evaluations.mjs';
import './evaluations.css';
const Select=({label,value,onChange,children,...props})=><select aria-label={label} value={value??''} onChange={e=>onChange(e.target.value)} {...props}>{children}</select>;
const Text=({label,value,onChange,rows=3,...props})=><Input.TextArea className="soft-focus-field" aria-label={label} value={value||''} onChange={e=>onChange(e.target.value)} autoSize={{minRows:rows,maxRows:18}} {...props}/>;
const Field=({label,children,hint})=><div className="eval-field"><label>{label}</label>{children}{hint&&<small>{hint}</small>}</div>;
const Lines=({label,values,onChange})=><Text label={label} rows={3} value={values.join('\n')} onChange={v=>onChange(v.split('\n'))}/>;
export function RubricEditor({dimensions,onChange}){
 const update=(i,patch)=>onChange(dimensions.map((d,n)=>n===i?{...d,...patch}:d));
 return <div className="rubric-editor"><p className="eval-muted">1 分明显不满足 · 3 分基本满足 · 5 分完全满足。总权重需为 100%。</p>{dimensions.map((d,i)=><div className="rubric-row" key={d.id}><Input className="soft-focus-field" aria-label={'维度 '+(i+1)+' 名称'} value={d.name} onChange={e=>update(i,{name:e.target.value})}/><label className="weight-field"><input aria-label={'维度 '+(i+1)+' 权重'} type="number" min="0" max="100" step="any" value={d.weight} onChange={e=>update(i,{weight:e.target.value===''?'':Number(e.target.value)})}/>%</label><Button aria-label={'移除维度 '+(i+1)} onClick={()=>onChange(dimensions.filter((_,n)=>n!==i))}>移除</Button><Text label={'维度 '+(i+1)+' 评分指引'} rows={1} value={d.guide} onChange={guide=>update(i,{guide})}/></div>)}<div className="eval-inline"><Button onClick={()=>onChange([...dimensions,{id:crypto.randomUUID(),name:'',weight:10,guide:''}])}>添加维度</Button><span className={Math.abs(dimensions.reduce((s,d)=>s+Number(d.weight),0)-100)>.001?'eval-error':''}>权重合计 {dimensions.reduce((s,d)=>s+Number(d.weight),0)}%</span></div></div>;
}
export function CaseEvaluationEditor({item,onChange}){
 const v=caseCriteria(item),patch=p=>onChange({...v,...p});
 return <section className="case-evaluation eval-scope"><h2>测评标准</h2><p className="eval-muted">用于正式测评任务；创建任务时会保存副本，不影响普通对比。</p><div className="eval-columns"><Field label="测评模块"><Select label="测评模块" value={v.module} onChange={module=>patch({module,scenario:SCENARIOS[module][0],dimensions:newRubric(module)})}>{Object.entries(MODULES).map(([k,n])=><option value={k} key={k}>{n}</option>)}</Select></Field><Field label="任务类型"><Select label="任务类型" value={v.scenario} onChange={scenario=>patch({scenario})}>{SCENARIOS[v.module].map(s=><option key={s}>{s}</option>)}</Select></Field></div>
 <Field label="参考材料 / 标准答案" hint="可填写原文、文档链接、测试命令或参考素材位置。"><Text label="参考材料" value={v.references} onChange={references=>patch({references})}/></Field>
 <Field label="硬性验收条件" hint="每行一项，至少一项；全部通过才视为合格。"><Lines label="硬性验收条件" values={v.acceptance} onChange={acceptance=>patch({acceptance})}/></Field>
 <Field label="严重错误" hint="每行一项；任一出现即验收不通过。"><Lines label="严重错误" values={v.severe} onChange={severe=>patch({severe})}/></Field>
 <details><summary>评分维度与权重</summary><RubricEditor dimensions={v.dimensions} onChange={dimensions=>patch({dimensions})}/></details></section>;
}
function TaskCreator({library,models,selected,seed,onSave,onCancel}){
 const [module,setModule]=useState(seed?.module||'text'),[name,setName]=useState(seed?seed.title+' · 测评':''),[scenario,setScenario]=useState(SCENARIOS[seed?.module||'text'][0]),[caseIds,setCaseIds]=useState(seed?[seed.case.id]:[]),[modelIds,setModelIds]=useState(seed?seed.models.map(m=>m.id):selected),[dimensions,setDimensions]=useState(newRubric(seed?.module||'text')),[conditions,setConditions]=useState(''),[caseOverrides,setCaseOverrides]=useState({}),[reviewer,setReviewer]=useState(''),[versions,setVersions]=useState({}),[error,setError]=useState('');
 const available=seed?[seed.case]:library.filter(c=>caseCriteria(c).module===module);
 const catalog=seed?seed.models:models;
 const changeModule=m=>{setModule(m);setScenario(SCENARIOS[m][0]);setDimensions(newRubric(m));setCaseIds([])};
 const submit=e=>{e.preventDefault();try{onSave(createTask({name,module,scenario,models:catalog.filter(m=>modelIds.includes(m.id)).map(m=>({...m,version:versions[m.id]||m.version})),cases:available.filter(c=>caseIds.includes(c.id)).map(c=>({...c,evaluation:{...caseCriteria(c,module),...caseOverrides[c.id]}})),dimensions,conditions,reviewer,seed}))}catch(e){setError(e.message)}};
 return <form onSubmit={submit}><div className="library-heading"><div><h1>新建测评任务</h1><p>固定测试条件，用多个用例比较同一组模型。</p></div></div>{seed&&<p className="eval-notice">本轮回答将作为预置演示副本加入，耗时和费用不视为实测。原对话保持独立。</p>}
 <Field label="任务名称"><Input className="soft-focus-field" aria-label="任务名称" value={name} maxLength={80} onChange={e=>setName(e.target.value)} placeholder="例如：退款客服模型选型"/></Field>
 <div className="eval-columns"><Field label="测评模块"><Select label="任务测评模块" value={module} onChange={changeModule} disabled={!!seed}>{Object.entries(MODULES).map(([k,n])=><option value={k} key={k}>{n}</option>)}</Select></Field><Field label="场景 / 任务类型"><Select label="任务场景" value={scenario} onChange={setScenario}>{SCENARIOS[module].map(s=><option key={s}>{s}</option>)}</Select></Field></div>
 <Field label="测评用例" hint="可多选；题库中的问题、参考材料和验收条件会固定到任务。">{!available.length?<p className="eval-notice">题库中还没有此模块的用例，请先到“我的题库”新增。</p>:<div className="eval-check-list">{available.map(c=><Checkbox key={c.id} checked={caseIds.includes(c.id)} onChange={e=>{const ids=e.target.checked?[...caseIds,c.id]:caseIds.filter(id=>id!==c.id);setCaseIds(ids);if(!caseIds.length&&e.target.checked){setDimensions(caseCriteria(c,module).dimensions);setScenario(caseCriteria(c,module).scenario)}}}>{c.title}</Checkbox>)}</div>}</Field>
 {caseIds.length>0&&<details><summary>核对用例与验收条件（{caseIds.length} 个）</summary>{available.filter(c=>caseIds.includes(c.id)).map(c=>{const v={...caseCriteria(c,module),...caseOverrides[c.id]},patch=p=>setCaseOverrides({...caseOverrides,[c.id]:{...v,...p}});return <section key={c.id}><h2>{c.title}</h2><pre>{c.question}</pre><Field label="参考材料 / 标准答案"><Text label={c.title+' 参考材料'} value={v.references} onChange={references=>patch({references})}/></Field><Field label="硬性验收条件（每行一项）"><Lines label={c.title+' 验收条件'} values={v.acceptance} onChange={acceptance=>patch({acceptance})}/></Field><Field label="严重错误（每行一项）"><Lines label={c.title+' 严重错误'} values={v.severe} onChange={severe=>patch({severe})}/></Field></section>})}<p className="eval-muted">仅修改本次任务副本，题库原文保持不变。</p></details>}
 <Field label="参与模型（2–9 个）" hint="仅记录配置。人工测评需在外部运行后录入结果；请填写实际版本。"><div className="eval-model-list">{catalog.map(m=><div key={m.id}><Checkbox disabled={!!seed} checked={modelIds.includes(m.id)} onChange={e=>setModelIds(e.target.checked?[...modelIds,m.id]:modelIds.filter(id=>id!==m.id))}>{m.name||m.model}</Checkbox>{modelIds.includes(m.id)&&<Input className="soft-focus-field" aria-label={(m.name||m.model)+' 版本'} placeholder="版本 / 日期（未知可留空）" value={versions[m.id]||''} onChange={e=>setVersions({...versions,[m.id]:e.target.value})}/>}</div>)}</div></Field>
 <Field label="共同测试条件" hint="记录温度、采样参数、分辨率、时长、运行环境等；不要填写密钥。条件变化时请新建任务。"><Text label="共同测试条件" value={conditions} onChange={setConditions}/></Field>
 <Field label="默认评价人"><Input className="soft-focus-field" aria-label="默认评价人" value={reviewer} onChange={e=>setReviewer(e.target.value)}/></Field>
 <details open><summary>统一评分模板</summary><p className="eval-muted">初始值来自首个选中用例。所有用例共用此模板；创建后固定。</p><RubricEditor dimensions={dimensions} onChange={setDimensions}/></details>
 {error&&<p role="alert" className="eval-error">{error}</p>}<div className="eval-actions"><Button onClick={onCancel}>取消</Button><Button type="primary" htmlType="submit">创建任务</Button></div></form>;
}
const SCORE_OPTIONS=<><option value="">未测</option>{[1,2,3,4,5].map(n=><option value={n} key={n}>{n} 分</option>)}<option value="na">不适用</option></>;
function RunEditor({task,run,onSave,onCancel}){
 const [v,setV]=useState(structuredClone(run)),[error,setError]=useState('');
 const c=task.cases.find(c=>c.id===run.caseId),m=task.models.find(m=>m.id===run.modelId),index=task.models.indexOf(m),q=qualityScore(task,v),gate=acceptanceStatus(task,v);
 const patch=p=>setV({...v,...p});const nested=(key,k,value)=>patch({[key]:{...v[key],[k]:value}});
 const readOnly=task.runs.some(r=>r.retryOf===run.id);
 const submit=e=>{e.preventDefault();try{onSave(saveRun(task,v))}catch(e){setError(e.message)}};
 return <form onSubmit={submit} className="run-editor"><Button onClick={onCancel}>返回任务</Button><div className="library-heading"><div><h1>{'ABCDEFGHI'[index]} · {m.name}</h1><p>{c.title} · 第 {run.repetition} 次独立测评 · 第 {run.attempt} 次尝试 · {sourceLabel(run.source)}</p></div></div>
 <details className="eval-conditions"><summary>查看本次固定条件与用例</summary><p><b>问题</b></p><pre>{c.question}</pre><p><b>系统提示词</b></p><pre>{c.systemPrompt}</pre><p><b>参考材料</b></p><pre>{c.evaluation.references||'未提供'}</pre><p>模型 ID：{m.apiId||m.id} · 版本：{m.version}</p><pre>{task.conditions||'未记录额外条件'}</pre></details>
 {readOnly&&<p className="eval-notice">已创建后续重试，此次记录保留为只读证据。</p>}
 <fieldset disabled={readOnly}><h2>原始结果</h2><Field label="运行状态"><Select label="运行状态" value={v.status} onChange={status=>patch({status})}><option value="pending">待录入</option><option value="success">已完成输出</option><option value="error">调用失败</option></Select></Field>
 <Field label="原始输出" hint="粘贴完整回答、代码、理解结果或测试日志。"><Text label="原始输出" rows={6} value={v.output} onChange={output=>patch({output})} readOnly={run.source==='demo'}/></Field>
 <Field label="图片 / 视频 / 文件引用" hint="记录文件名或可访问链接；导出保存引用，不包含文件本体。"><Text label="媒体引用" value={v.assets} onChange={assets=>patch({assets})}/></Field>
 {v.status==='error'&&<Field label="失败原因"><Text label="失败原因" value={v.failure} onChange={failure=>patch({failure})}/></Field>}
 <Field label="实际运行时间（含时区，可选）"><Input className="soft-focus-field" aria-label="实际运行时间" placeholder="例如 2026-09-22 14:30 +08:00" value={v.executedAt||''} onChange={e=>patch({executedAt:e.target.value})}/></Field>
 <div className="eval-inline"><strong>直观偏好</strong>{['更好','较差'].map((label,i)=><button type="button" className={'eval-preference '+(v.preference===label?(i?'negative':'positive'):'')} aria-pressed={v.preference===label} key={label} onClick={()=>patch({preference:v.preference===label?'':label})}>{label}</button>)}</div>
 <h2>验收与严重错误 <span className={'eval-status '+gate}>{statusLabel(gate)}</span></h2>
 <p className="eval-muted">硬性条件全部通过、严重错误均未出现，才计为合格成果。</p>
 {c.evaluation.acceptance.map((text,i)=><div className="eval-rating-row" key={'a'+i}><span>{text}</span><Select label={'验收 '+(i+1)} value={v.acceptance[i]} onChange={value=>nested('acceptance',i,value)}><option value="">待评价</option><option value="pass">通过</option><option value="fail">不通过</option></Select></div>)}
 {c.evaluation.severe.map((text,i)=><div className="eval-rating-row" key={'s'+i}><span>{text}</span><Select label={'严重错误 '+(i+1)} value={v.severe[i]} onChange={value=>nested('severe',i,value)}><option value="">待确认</option><option value="no">未出现</option><option value="yes">出现</option></Select></div>)}
 <h2>质量评分 <span className="eval-status">{q.score===null?'未完成':q.score+' / 100'}</span></h2><p className="eval-muted">未测会保留空缺。不适用维度不计入权重，请在备注说明原因。</p>
 {task.dimensions.map(d=><div className="eval-rating-row" key={d.id}><div><strong>{d.name} <small>{d.weight}%</small></strong><p>{d.guide}</p></div><Select label={d.name+' 评分'} value={v.scores[d.id]} onChange={value=>nested('scores',d.id,value==='na'||value===''?value:Number(value))}>{SCORE_OPTIONS}</Select></div>)}
 <h2>评价依据</h2><Field label="证据位置" hint={task.module==='video'?'例如 00:12–00:16；注明镜头或帧。':task.module==='image'?'例如画面右上角、主体左手、文字区域。':task.module==='code'?'例如文件路径:行号、测试用例或日志行。':'例如第 2 段、异常情况第 3 条。'}><Input className="soft-focus-field" aria-label="证据位置" value={v.location} onChange={e=>patch({location:e.target.value})}/></Field>
 <Field label="证据摘录 / 测试结果"><Text label="证据摘录" value={v.evidence} onChange={evidence=>patch({evidence})}/></Field><Field label="评价备注 / 不适用原因"><Text label="评价备注" value={v.note} onChange={note=>patch({note})}/></Field><Field label="评价人"><Input className="soft-focus-field" aria-label="评价人" value={v.reviewer} onChange={e=>patch({reviewer:e.target.value})}/></Field>
 <div className="eval-columns"><Field label="是否采纳"><Select label="是否采纳" value={v.adoption} onChange={adoption=>patch({adoption})}><option value="">待确认</option><option>直接采纳</option><option>修改后采纳</option><option>不采纳</option></Select></Field><Field label="返工耗时（分钟，可选）"><input type="number" min="0" step="any" aria-label="返工耗时" value={v.reworkMinutes??''} onChange={e=>patch({reworkMinutes:e.target.value})}/></Field></div>
 <details><summary>耗时、费用与 Token（可选）</summary>{run.source==='demo'?<p className="eval-notice">演示记录不采集性能与费用，不使用页面里的示例耗时。</p>:<><p className="eval-muted">手工记录实际运行数据；留空即“未采集”，不会填入估算值。费用统一为人民币 CNY。</p><div className="eval-columns">{[['latency','总耗时（秒）'],['cost','本次费用（CNY）'],['inputTokens','输入 Token'],['outputTokens','输出 Token']].map(([key,label])=><Field key={key} label={label}><input type="number" min="0" step={key.includes('Tokens')?'1':'any'} aria-label={label} value={v.metrics[key]??''} onChange={e=>nested('metrics',key,e.target.value)}/></Field>)}</div><Field label="测量来源" hint="例如 API 返回 usage、账单日期、秒表记录；外币需记录换算依据。"><Text label="测量来源" value={v.measurementNote} onChange={measurementNote=>patch({measurementNote})}/></Field></>}</details>
 </fieldset>{error&&<p className="eval-error" role="alert">{error}</p>}<div className="eval-actions"><Button onClick={onCancel}>{readOnly?'返回':'取消'}</Button>{!readOnly&&<Button type="primary" htmlType="submit">保存测评</Button>}</div></form>;
}
function download(task,type){const content={md:()=>taskReport(task),detail:()=>detailCSV(task),summary:()=>summaryCSV(task),json:()=>rawPackage(task)}[type]();const ext=type==='detail'||type==='summary'?'csv':type;const name={md:'测评报告',detail:'逐项明细',summary:'汇总',json:'原始记录'}[type];const url=URL.createObjectURL(new Blob([content],{type:ext==='csv'?'text/csv;charset=utf-8':ext==='json'?'application/json':'text/markdown;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=task.name.replace(/[\\/:*?"<>|]/g,'_')+'-'+name+'.'+ext;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
function TaskDetail({task,onSave,onBack}){
 const {message,modal}=App.useApp();const [runId,setRunId]=useState(null),[report,setReport]=useState(false),[conclusion,setConclusion]=useState(task.conclusion),[tab,setTab]=useState('cases');
 const persist=next=>{if(onSave(next)!==false){message.success('已保存');return true}return false};
 const update=fn=>{try{persist(fn())}catch(e){message.error(e.message)}};
 const changeConclusion=patch=>setConclusion({...conclusion,...patch});
 const editRun=task.runs.find(r=>r.id===runId);
 if(editRun)return <RunEditor key={runId} task={task} run={editRun} onSave={next=>{if(persist(next)){setRunId(null);window.scrollTo(0,0)}}} onCancel={()=>modal.confirm({title:'返回任务？',content:'尚未保存的录入内容不会保留。',okText:'返回任务',cancelText:'继续编辑',onOk:()=>setRunId(null)})}/>;
 const groups=summarize(task),pending=task.runs.filter(r=>acceptanceStatus(task,r)==='pending').length;
 return <><Button onClick={onBack}>全部任务</Button><div className="library-heading"><div><h1>{task.name}</h1><p>{MODULES[task.module]} · {task.scenario} · {task.models.length} 个模型 · {task.cases.length} 个用例</p></div><Button onClick={()=>setReport(!report)}>{report?'收起报告':'预览报告'}</Button></div>
 <div className="eval-overview"><div><strong>{task.runs.length}</strong><span>尝试记录</span></div><div><strong>{pending}</strong><span>待完成验收</span></div><div><strong>{task.runs.filter(r=>r.source==='demo').length}</strong><span>预置演示记录</span></div></div>
 <div className="eval-export"><span>导出当前已保存内容</span>{[['md','完整报告 · MD'],['summary','汇总 · CSV'],['detail','明细 · CSV'],['json','原始记录 · JSON']].map(([k,label])=><Button key={k} onClick={()=>download(task,k)}>{label}</Button>)}</div>
 {report&&<section className="eval-report"><h2>报告预览</h2><pre>{taskReport(task)}</pre></section>}
 <nav className="eval-tabs" aria-label="测评任务内容">{[['cases','用例与记录'],['summary','结果汇总'],['conditions','固定条件'],['conclusion','选型结论']].map(([key,label])=><button type="button" key={key} aria-current={tab===key?'page':undefined} onClick={()=>setTab(key)}>{label}</button>)}</nav>
 {tab==='cases'&&<><p className="eval-muted">每次新增独立测评为全部模型建立一组空记录。完成外部运行后，录入原始结果并评分。</p>{task.cases.map(c=><section className="eval-case" key={c.id}><div className="eval-case-heading"><div><h2>{c.title}</h2><p>{c.question}</p></div><Button onClick={()=>update(()=>addExperiment(task,c.id))}>新增独立测评</Button></div><div className="eval-runs">{task.runs.filter(r=>r.caseId===c.id).map(r=>{const model=task.models.find(m=>m.id===r.modelId),gate=acceptanceStatus(task,r),q=qualityScore(task,r),retry=task.runs.some(x=>x.retryOf===r.id);return <article className="eval-run" key={r.id}><div><strong>{'ABCDEFGHI'[task.models.indexOf(model)]} · {model.name}</strong><p>{sourceLabel(r.source)} · 重复 {r.repetition} / 尝试 {r.attempt}</p></div><div className="eval-run-result"><span className={'eval-status '+gate}>{r.status==='error'?'调用失败':statusLabel(gate)}</span><span>{q.score===null?'未完成评分':q.score+' 分'}</span></div><div className="eval-inline"><Button aria-label={'评价 '+model.name+' '+c.title+' '+r.repetition+'-'+r.attempt} onClick={()=>{setRunId(r.id);window.scrollTo(0,0)}}>{retry?'查看记录':'录入 / 评价'}</Button>{gate==='fail'&&!retry&&r.source!=='demo'&&<Button onClick={()=>update(()=>retryRun(task,r.id))}>失败重试</Button>}</div></article>})}{!task.runs.some(r=>r.caseId===c.id)&&<p className="eval-empty">还没有记录，点击“新增独立测评”开始。</p>}</div></section>)}</>}
 {tab==='summary'&&<><h2>模型总览</h2><p className="eval-muted">各用例等权平均。所有用例和评分完成后才显示总分；不同“不适用”范围不会混算。</p><div className="eval-model-summary">{modelSummaries(task).map(s=><article key={s.model+s.source}><strong>{s.model}</strong><small>{sourceLabel(s.source)}</small><b>{s.quality===null?'—':s.quality}<small> / 100</small></b><p>{s.qualityStatus}</p><p>用例覆盖 {s.cases}/{s.totalCases} · 首过 {s.firstPass}/{s.firstEvaluated}<br/>最终合格 {s.accepted}/{s.resolved} 已验收</p></article>)}</div><h2>逐用例汇总</h2><p className="eval-muted">按模型 × 用例 × 来源分别统计。首过率只统计已验收的首次尝试；质量取每次独立测评的最后一次尝试。</p>{!groups.length?<p className="eval-empty">完成录入后，这里会显示汇总。</p>:<div className="eval-table-scroll"><table><thead><tr>{['模型 / 用例','来源','重复 / 重试','首过 / 首评','最终合格 / 已验收','质量 / 样本','耗时 / 样本','合格成本'].map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{groups.map(s=><tr key={s.modelId+s.caseId+s.source}><th>{s.model}<small>{s.caseTitle}</small></th><td>{sourceLabel(s.source)}</td><td>{s.repetitions} / {s.retries}</td><td>{s.firstPass} / {s.firstEvaluated}</td><td>{s.accepted} / {s.resolved}</td><td>{s.comparable?s.quality??'未评分':'维度不同'} / {s.scoreCount}</td><td>{s.latency===null?'未采集':s.latency+' s'} / {s.latencyCount}</td><td>{s.costPerAccepted===null?s.costStatus:s.costPerAccepted.toFixed(3)+' CNY'}</td></tr>)}</tbody></table></div>}</>}
 {tab==='conditions'&&<section><p className="eval-notice">以下为创建时的快照。修改题库或模型配置不会改变此任务；改变测试条件请新建任务。</p><h2>模型</h2>{task.models.map((m,i)=><p key={m.id}>{'ABCDEFGHI'[i]} · {m.name} · {m.apiId||m.id} · {m.version}</p>)}<h2>共同条件</h2><pre>{task.conditions||'未记录额外条件'}</pre><h2>统一评分标准</h2>{task.dimensions.map(d=><p key={d.id}>{d.name} · {d.weight}%<br/><span className="eval-muted">{d.guide}</span></p>)}{task.cases.map(c=><details key={c.id}><summary>{c.title} · 用例快照</summary><pre>{c.question}</pre><pre>{c.systemPrompt}</pre><p>参考材料：{c.evaluation.references||'未填写'}</p><p>验收：{c.evaluation.acceptance.join('；')}</p><p>严重错误：{c.evaluation.severe.join('；')||'无额外项'}</p></details>)}</section>}
 {tab==='conclusion'&&<section><p className="eval-notice">结合汇总与原始证据填写。演示数据、未完成评分或样本不足不能支持真实选型结论。</p><Field label="推荐模型 / 方案"><Input className="soft-focus-field" aria-label="推荐模型" value={conclusion.recommended} onChange={e=>changeConclusion({recommended:e.target.value})}/></Field><Field label="适用场景"><Text label="适用场景" value={conclusion.suitable} onChange={suitable=>changeConclusion({suitable})}/></Field><Field label="不适用场景"><Text label="不适用场景" value={conclusion.unsuitable} onChange={unsuitable=>changeConclusion({unsuitable})}/></Field><Field label="结论依据 / 待验证事项"><Text label="结论依据" value={conclusion.reason} onChange={reason=>changeConclusion({reason})}/></Field><Button type="primary" onClick={()=>persist({...task,conclusion})}>保存结论</Button></section>}
 </>;
}
export default function Evaluations({tasks,onSave,library,models,selected,seed,onClearSeed}){
 const {message,modal}=App.useApp();const [creating,setCreating]=useState(!!seed),[activeId,setActiveId]=useState(null),[query,setQuery]=useState('');
 const active=tasks.find(t=>t.id===activeId);
 const save=task=>onSave(tasks.some(t=>t.id===task.id)?tasks.map(t=>t.id===task.id?task:t):[task,...tasks]);
 return <main id="main" className="evaluation-page eval-scope">{creating?<TaskCreator library={library} models={models} selected={selected} seed={seed} onSave={task=>{if(save(task)!==false){setCreating(false);setActiveId(task.id);window.scrollTo(0,0);onClearSeed();message.success('测评任务已创建，条件已固定')}}} onCancel={()=>{setCreating(false);onClearSeed()}}/>:active?<TaskDetail key={active.id} task={active} onSave={save} onBack={()=>setActiveId(null)}/>:<><div className="library-heading"><div><h1>测评任务</h1><p>记录条件、保留证据，用完整报告支持模型选型。</p></div><Button type="primary" onClick={()=>{setCreating(true);window.scrollTo(0,0)}}>新建测评任务</Button></div><div className="library-toolbar"><span>共 {tasks.length} 个任务</span><Input className="soft-focus-field" aria-label="搜索测评任务" placeholder="搜索任务名称" value={query} onChange={e=>setQuery(e.target.value)}/></div>{tasks.filter(t=>t.name.includes(query)).map(t=><article className="eval-task-card" key={t.id}><div><h2>{t.name}</h2><p>{MODULES[t.module]} · {t.scenario} · {t.cases.length} 个用例 · {t.runs.length} 条记录</p><small>{new Date(t.createdAt).toLocaleDateString('zh-CN')}</small></div><div className="eval-inline"><Button onClick={()=>{setActiveId(t.id);window.scrollTo(0,0)}}>打开任务</Button><Button danger onClick={()=>modal.confirm({title:'删除测评任务？',content:'将删除任务和其中的评价记录，题库与原对话不受影响。请先导出需要的报告。',okText:'删除',cancelText:'取消',onOk:()=>onSave(tasks.filter(x=>x.id!==t.id))})}>删除</Button></div></article>)}{!tasks.length&&<div className="eval-empty"><h2>从一组用例开始</h2><p>1. 在题库设置验收标准　2. 固定模型与条件　3. 录入、评价并导出</p><p>文本、图片、视频、代码均可人工测评。现有演示对话也可建立独立任务。</p></div>}{tasks.length>0&&!tasks.some(t=>t.name.includes(query))&&<p className="eval-empty">没有匹配的任务。</p>}</>}</main>;
}
